/* ================= ASSETS (Blender GLB) ================= */
const LOOT_MESH=['camera_b','vial','badge','wrench','ledger','tin','bunny','radio_h','sextant','film','mineral','typewriter','jar','doll','blade','clock','bust','drive','statue','coil','painting','cryo','meteorite','visor','organ','cube','map','egg','ledger','anchor','tape','camera_w','mask','phone_b','photo','key'];
const COS_MESH={hair:['Hair_Buzz','Hair_Mop','Hair_Ponytail',null,'Hair_Mohawk','Hair_Beanie','Hair_Afro','Hair_Bun','Hair_Long','Hair_Braids'],face:[null,'Face_Grin','Face_Worried','Face_Mustache','Face_Goggles','Face_Bandana','Face_GasMask','Face_Hockey','Face_Shades','Face_Monocle','Face_Clown','Face_Eyepatch','Face_Beard','Face_Company'],outfit:[null,'Outfit_Explorer','Outfit_Hazmat','Outfit_Expedition','Outfit_Office','Outfit_Pajamas','Outfit_Tux','Outfit_Knight','Outfit_Hoodie','Outfit_Company'],helmet:[null,'Helmet_HardHat','Helmet_Oversized','Helmet_MinerLamp','Helmet_Colander','Helmet_Cone','Helmet_TopHat','Helmet_Crown','Helmet_CatEars','Helmet_Horns','Helmet_Halo','Helmet_Party','Helmet_Astro','Helmet_Viking','Helmet_Chef','Helmet_Bucket'],pack:['Pack_Standard','Pack_Ridiculous','Pack_Duffel','Pack_Purse','Pack_Propane','Pack_Jetpack','Pack_Coffin','Pack_Teddy','Pack_Rocket'],acc:[null,'Acc_Glow','Acc_Lanyard','Acc_Fanny','Acc_Scarf','Acc_Duck','Acc_Cape','Acc_Wings','Acc_Bowtie','Acc_Medal','Acc_Chain','Acc_Tail','Acc_Badge']};
const Assets={g:{},ready:false,err:null,prog:0,
 files:{player:'player/player.glb',van:'vehicles/van.glb',props:'props/props.glb',loot:'loot/loot.glb',echo:'creatures/echo.glb',crawler:'creatures/crawler.glb',lighteater:'creatures/lighteater.glb',window:'creatures/window.glb',hound:'creatures/hound.glb',stack:'creatures/stack.glb',drifter:'creatures/drifter.glb',warden:'creatures/warden.glb',mourner:'creatures/mourner.glb',hanger:'creatures/hanger.glb',collector:'creatures/collector.glb',sleeper:'creatures/sleeper.glb',mimic:'creatures/mimic.glb',swarm:'creatures/swarm.glb',burrower:'creatures/burrower.glb',twin:'creatures/twin.glb'},
 load(onDone,onProg){const L=new THREE.GLTFLoader();if(THREE.DRACOLoader){const d=new THREE.DRACOLoader();d.setDecoderPath('https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/libs/draco/');L.setDRACOLoader(d);}
  const keys=Object.keys(this.files);let done=0,idx=0,active=0;const self=this;
  const finish=(k,g)=>{g.scene.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material&&o.material.transparent){o.material.depthWrite=false;}}});self.g[k]=g;done++;self.prog=done/keys.length;onProg&&onProg(self.prog);if(done===keys.length){self.ready=true;onDone();}};
  const one=(k,tries)=>{active++;L.load('models/'+self.files[k]+'?v=7',g=>{active--;finish(k,g);next();},undefined,e=>{active--;if(tries<3){setTimeout(()=>one(k,tries+1),800*(tries+1));}else{self.err='Failed to load models/'+self.files[k]+' after 3 tries. Check your connection and reload.';onProg&&onProg(self.prog);console.error(e);}});};
  const next=()=>{while(active<4&&idx<keys.length){one(keys[idx++],0);}};next();},
 node(lib,name){const g=this.g[lib];if(!g)return null;let o=g.scene.getObjectByName(name);if(!o&&lib==='props'&&name==='window_frame')o=g.scene.children.find(c=>c.name.indexOf('window')===0);return o;},
 clone(lib,name){const o=this.node(lib,name);if(!o){const m=new THREE.Mesh(new THREE.BoxGeometry(0.4,0.4,0.4),new THREE.MeshStandardMaterial({color:0xff00ff}));return m;}const c=o.clone();c.position.set(0,0,0);if(name!=='Door_L'&&name!=='Door_R')c.rotation.set(0,0,0);const noCast=lib==='props'&&/^(lamp|lamp_emergency|vent|doorframe|window_frame|beacon|lamppost|sample_station)$/.test(name);c.traverse(m=>{if(m.isMesh){m.castShadow=!noCast;m.receiveShadow=true;}});return c;},
 rig(lib){const g=this.g[lib];if(!g)return null;const root=THREE.SkeletonUtils.clone(g.scene);const mixer=new THREE.AnimationMixer(root);const acts={};for(const c of g.animations){const nm=c.name.split('|').pop().replace(/^.*\./,'');acts[nm]=mixer.clipAction(c);acts[c.name]=acts[nm];}root.traverse(m=>{if(m.isMesh){m.castShadow=true;m.receiveShadow=true;m.frustumCulled=false;}});return {root,mixer,acts,cur:null,play(n,fade,once){const a=this.acts[n];if(!a||a===this.cur)return;if(this.cur)this.cur.fadeOut(fade||0.2);a.reset();a.setLoop(once?THREE.LoopOnce:THREE.LoopRepeat);a.clampWhenFinished=!!once;a.fadeIn(fade||0.2).play();this.cur=a;}};},
 bbox:{},size(lib,name){const k=lib+':'+name;if(this.bbox[k])return this.bbox[k];const o=this.node(lib,name);if(!o){return this.bbox[k]={r:0.2,h:0.3};}const b=new THREE.Box3().setFromObject(o);const s=new THREE.Vector3();b.getSize(s);return this.bbox[k]={r:Math.max(s.x,s.z)/2,h:s.y,minY:b.min.y};}
};
/* ================= SHADERS ================= */
const SHU={time:{value:0}};
const CR_SHADE={echo:{rim:0x3050c0,rp:3.0,rs:0.7,bump:0.3},crawler:{rim:0xa05010,rp:3.5,rs:0.5,bump:0.35},lighteater:{rim:0xff6a10,rp:2.5,rs:0.6,pulse:0.9,bump:0.4,vein:0xff6a10},window:{rim:0xd0d0e0,rp:4.0,rs:0.5,bump:0.2},hound:{rim:0x40ff70,rp:3.5,rs:0.5,bump:0.35},stack:{rim:0xffb040,rp:4.0,rs:0.25,bump:0.1},drifter:{rim:0x60e0ff,rp:2.0,rs:1.4,pulse:0.6,bump:0.15,vein:0x60e0ff},warden:{rim:0xff3010,rp:3.0,rs:0.8,pulse:0.7,bump:0.3,vein:0xff2010},mourner:{rim:0x8040c0,rp:3.5,rs:0.6,bump:0.25},hanger:{rim:0x706050,rp:4.0,rs:0.3,bump:0.4},collector:{rim:0xffb020,rp:3.5,rs:0.5,bump:0.3},sleeper:{rim:0xff5010,rp:3.0,rs:0.5,pulse:0.5,bump:0.35,vein:0xff5010},mimic:{rim:0xd0a040,rp:4.0,rs:0.3,bump:0.15},swarm:{rim:0x80ff80,rp:2.0,rs:0.7,pulse:0.5,bump:0},burrower:{rim:0x806040,rp:3.5,rs:0.5,bump:0.4},twin:{rim:0xff4040,rp:4.5,rs:0.3,bump:0.15},player:{rim:0x4060a0,rp:4.0,rs:0.35,bump:0.12}};
function enhanceRig(root,kind){const cfg=CR_SHADE[kind]||CR_SHADE.player;const dis={value:0};root.userData.dissolve=dis;const hit={value:0};root.userData.hit=hit;const veinC=new THREE.Color(cfg.vein||0x000000);
  root.traverse(m=>{if(!m.isMesh&&!m.isSkinnedMesh)return;if(!m.material)return;m.material=m.material.clone();const mat=m.material;const pulse=(cfg.pulse&&mat.emissive&&(mat.emissive.r+mat.emissive.g+mat.emissive.b)>0.3)?cfg.pulse:0;const rimC=new THREE.Color(cfg.rim);
    mat.onBeforeCompile=sh=>{sh.uniforms.uTime=SHU.time;sh.uniforms.uRim={value:rimC};sh.uniforms.uRimP={value:cfg.rp};sh.uniforms.uRimS={value:cfg.rs};sh.uniforms.uPulse={value:pulse};sh.uniforms.uDis=dis;sh.uniforms.uHit=hit;sh.uniforms.uBump={value:cfg.bump||0};sh.uniforms.uVein={value:veinC};
      sh.vertexShader=('varying vec3 vWp;\n'+sh.vertexShader).replace('#include <project_vertex>','#include <project_vertex>\nvWp=(modelMatrix*vec4(transformed,1.0)).xyz;');
      sh.fragmentShader=('uniform float uTime;uniform vec3 uRim;uniform float uRimP;uniform float uRimS;uniform float uPulse;uniform float uDis;uniform float uHit;uniform float uBump;uniform vec3 uVein;varying vec3 vWp;\nfloat hash3(vec3 p){return fract(sin(dot(p,vec3(12.9898,78.233,45.164)))*43758.5453);}\nfloat vnoise(vec3 p){vec3 i=floor(p);vec3 f=fract(p);f=f*f*(3.0-2.0*f);float a=hash3(i),b=hash3(i+vec3(1,0,0)),c=hash3(i+vec3(0,1,0)),d=hash3(i+vec3(1,1,0)),e=hash3(i+vec3(0,0,1)),f1=hash3(i+vec3(1,0,1)),g=hash3(i+vec3(0,1,1)),h=hash3(i+vec3(1,1,1));return mix(mix(mix(a,b,f.x),mix(c,d,f.x),f.y),mix(mix(e,f1,f.x),mix(g,h,f.x),f.y),f.z);}\n'+sh.fragmentShader).replace('#include <normal_fragment_maps>','#include <normal_fragment_maps>\nif(uBump>0.0){vec3 bp=vWp*22.0;float n0=vnoise(bp);vec3 bg=vec3(vnoise(bp+vec3(0.3,0.0,0.0))-n0,vnoise(bp+vec3(0.0,0.3,0.0))-n0,vnoise(bp+vec3(0.0,0.0,0.3))-n0);float n1=vnoise(vWp*5.0);normal=normalize(normal+bg*uBump*4.0*(0.5+n1));}').replace('#include <clipping_planes_fragment>','#include <clipping_planes_fragment>\n float dn=fract(sin(dot(floor(vViewPosition.xyz*7.0),vec3(12.9898,78.233,45.164)))*43758.5453);if(dn<uDis)discard;')
        .replace('#include <dithering_fragment>','float rimF=pow(1.0-clamp(dot(normalize(vNormal),normalize(vViewPosition)),0.0,1.0),uRimP);gl_FragColor.rgb+=uRim*rimF*uRimS*(0.75+0.25*sin(uTime*2.3+vViewPosition.y*3.0));gl_FragColor.rgb+=gl_FragColor.rgb*uPulse*(0.5+0.5*sin(uTime*3.1));if(uDis>0.0){gl_FragColor.rgb+=vec3(1.0,0.5,0.2)*smoothstep(0.0,0.12,uDis-dn+0.12)*2.0;}float vn=smoothstep(0.84,1.0,vnoise(vWp*7.0+vec3(0.0,uTime*0.12,0.0)));gl_FragColor.rgb+=uVein*vn*(0.7+0.5*sin(uTime*2.2+vWp.y*4.0));gl_FragColor.rgb=mix(gl_FragColor.rgb,vec3(1.0,0.35,0.25),uHit*0.75);\n#include <dithering_fragment>');};
    mat.needsUpdate=true;});}
function enhanceSurface(mat,wet){mat.onBeforeCompile=sh=>{sh.uniforms.uTime=SHU.time;sh.uniforms.uWet={value:wet?1.0:0.0};
  sh.fragmentShader=('uniform float uTime;uniform float uWet;\n'+sh.fragmentShader).replace('#include <roughnessmap_fragment>','#include <roughnessmap_fragment>\n{float pn=fract(sin(dot(floor(vUv*26.0),vec2(12.9898,78.233)))*43758.5453);float pn2=fract(sin(dot(floor(vUv*7.0)+3.0,vec2(39.3,11.7)))*24634.6);float wetSpot=smoothstep(0.55,0.9,pn2)*uWet;roughnessFactor=mix(roughnessFactor,roughnessFactor*(0.6+0.5*pn),0.5);roughnessFactor=mix(roughnessFactor,0.08+0.05*sin(uTime*1.7+pn*6.0),wetSpot);}');};mat.needsUpdate=true;}
/* ================= WORLD ================= */
const G={state:'title',map:null,scene:null,cam:null,ren:null,objs:[],objById:{},creatures:[],doors:{},lights:[],lightPool:[],props:[],docs:[],mission:null,t:0,gravity:18,stage:1,timer:0,total:0,avatars:{},pings:[],markers:[],van:null,vanZone:null,fx:{shake:0,blind:0,glitch:0},tips:{},lamps:{},flareObjs:[],rain:null,dust:null,elevator:null,hub:null,music:0,paused:false};
function mkTex(kind,rgb,rgb2){const N=512,c=document.createElement('canvas');c.width=c.height=N;const x=c.getContext('2d');x.fillStyle=rgb;x.fillRect(0,0,N,N);
  const id=x.getImageData(0,0,N,N),d=id.data;for(let i=0;i<d.length;i+=4){const n=(Math.random()-0.5)*(kind==='concrete'?40:22);d[i]+=n;d[i+1]+=n;d[i+2]+=n;}x.putImageData(id,0,0);
  /* large-scale mottling */for(let i=0;i<70;i++){const g=x.createRadialGradient(Math.random()*N,Math.random()*N,0,0,0,0);x.fillStyle='rgba(0,0,0,'+(Math.random()*0.08)+')';x.beginPath();x.arc(Math.random()*N,Math.random()*N,20+Math.random()*90,0,TAU);x.fill();}
  x.strokeStyle=rgb2||'rgba(0,0,0,0.4)';x.lineWidth=3;
  if(kind==='tiles'){for(let i=0;i<=N;i+=128){x.beginPath();x.moveTo(i,0);x.lineTo(i,N);x.moveTo(0,i);x.lineTo(N,i);x.stroke();}x.strokeStyle='rgba(255,255,255,0.06)';x.lineWidth=1;for(let i=2;i<=N;i+=128){x.beginPath();x.moveTo(i,0);x.lineTo(i,N);x.moveTo(0,i);x.lineTo(N,i);x.stroke();}}
  else if(kind==='panel'){for(let i=0;i<=N;i+=256){x.beginPath();x.moveTo(i,0);x.lineTo(i,N);x.stroke();}x.beginPath();x.moveTo(0,400);x.lineTo(N,400);x.stroke();x.fillStyle='rgba(0,0,0,0.25)';x.fillRect(0,400,N,112);for(let i=0;i<24;i++){x.fillStyle='rgba(0,0,0,0.35)';x.beginPath();x.arc(24+Math.floor(i/2)*44,(i%2?60:340),3,0,TAU);x.fill();}}
  else if(kind==='grate'){for(let i=0;i<=N;i+=64){x.beginPath();x.moveTo(i,0);x.lineTo(i,N);x.moveTo(0,i);x.lineTo(N,i);x.stroke();}}
  else if(kind==='brick'){for(let row=0;row<8;row++){const y=row*64;const off=(row%2)*64;for(let col=-1;col<5;col++){x.fillStyle='rgba(0,0,0,0.45)';x.fillRect(0,y,N,5);x.fillRect(col*128+off,y,5,64);x.fillStyle='rgba(0,0,0,'+(Math.random()*0.16)+')';x.fillRect(col*128+off+5,y+5,123,59);}}}
  else if(kind==='wood'){for(let i=0;i<8;i++){const y=i*64;x.fillStyle='rgba(0,0,0,'+(0.08+Math.random()*0.14)+')';x.fillRect(0,y,N,64);x.fillStyle='rgba(0,0,0,0.5)';x.fillRect(0,y,N,3);for(let g=0;g<6;g++){x.fillStyle='rgba(0,0,0,'+(Math.random()*0.12)+')';x.fillRect(0,y+6+g*9+Math.random()*4,N,1+Math.random()*2);}x.fillStyle='rgba(0,0,0,0.5)';x.fillRect(Math.random()*N,y,3,64);}}
  else if(kind==='stone'){for(let row=0;row<6;row++){const y=row*86;let cx=-(Math.random()*60);while(cx<N){const w=60+Math.random()*110;x.fillStyle='rgba(0,0,0,'+(0.05+Math.random()*0.2)+')';x.fillRect(cx+4,y+4,w-8,78);x.strokeStyle='rgba(0,0,0,0.6)';x.lineWidth=5;x.strokeRect(cx+2,y+2,w-4,82);x.fillStyle='rgba(255,255,255,0.05)';x.fillRect(cx+6,y+6,w-12,3);cx+=w;}}}
  else if(kind==='plaster'){for(let i=0;i<9;i++){x.strokeStyle='rgba(0,0,0,'+(0.3+Math.random()*0.4)+')';x.lineWidth=1+Math.random()*2;x.beginPath();let px=Math.random()*N,py=Math.random()*N;x.moveTo(px,py);for(let j=0;j<6;j++){px+=(Math.random()-0.5)*90;py+=(Math.random()-0.5)*90;x.lineTo(px,py);}x.stroke();}for(let i=0;i<5;i++){x.fillStyle='rgba(0,0,0,'+(0.15+Math.random()*0.2)+')';x.beginPath();x.arc(Math.random()*N,Math.random()*N,15+Math.random()*40,0,TAU);x.fill();}x.fillStyle='rgba(0,0,0,0.35)';x.fillRect(0,420,N,92);}
  else if(kind==='rust'){for(let i=0;i<=N;i+=256){x.beginPath();x.moveTo(i,0);x.lineTo(i,N);x.stroke();}for(let i=0;i<40;i++){x.fillStyle='rgba(120,50,10,'+(0.15+Math.random()*0.35)+')';x.fillRect(Math.random()*N,Math.random()*N,4+Math.random()*30,20+Math.random()*160);}for(let i=0;i<24;i++){x.fillStyle='rgba(0,0,0,0.4)';x.beginPath();x.arc(24+Math.floor(i/2)*44,(i%2?60:340),3,0,TAU);x.fill();}}
  else if(kind==='stripes'){x.fillStyle='rgba(0,0,0,0.5)';for(let i=-N;i<N*2;i+=128){x.beginPath();x.moveTo(i,0);x.lineTo(i+64,0);x.lineTo(i+64-N,N);x.lineTo(i-N,N);x.fill();}}
  for(let i=0;i<60;i++){x.fillStyle='rgba(0,0,0,'+(Math.random()*0.28)+')';x.fillRect(Math.random()*N,Math.random()*N,Math.random()*80,Math.random()*16);}
  for(let i=0;i<30;i++){x.fillStyle='rgba(255,255,255,'+(Math.random()*0.05)+')';x.fillRect(Math.random()*N,Math.random()*N,Math.random()*40,Math.random()*6);}
  const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.anisotropy=8;return t;}
function hex(c){return '#'+c.toString(16).padStart(6,'0');}
function initRenderer(){const ren=new THREE.WebGLRenderer({canvas:$('gl'),antialias:S.set.gfx>=2,powerPreference:'high-performance'});ren.setPixelRatio(Math.min(devicePixelRatio,S.set.gfx>=3?2:S.set.gfx>=2?1.5:S.set.gfx>=1?1:0.75));ren.setSize(innerWidth,innerHeight);ren.shadowMap.enabled=S.set.gfx>=2;ren.shadowMap.type=THREE.PCFSoftShadowMap;ren.outputEncoding=THREE.sRGBEncoding;ren.toneMapping=THREE.ACESFilmicToneMapping;ren.toneMappingExposure=1.0*S.set.bright;G.ren=ren;
  G.cam=new THREE.PerspectiveCamera(S.set.fov,innerWidth/innerHeight,0.05,120);addEventListener('resize',()=>{ren.setSize(innerWidth,innerHeight);G.cam.aspect=innerWidth/innerHeight;G.cam.updateProjectionMatrix();if(G.composer){attachComposer();}});}
const EDGE_SHADER={uniforms:{tDiffuse:{value:null},tDepth:{value:null},res:{value:new THREE.Vector2(1,1)},near:{value:0.05},far:{value:120},strength:{value:0.9},time:{value:0},uRain:{value:0},uAberr:{value:0},uHurt:{value:0},uBlind:{value:0},uDanger:{value:0},uPulse:{value:0},uGrain:{value:0.028},uGrade:{value:0.45}},
 vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',
 fragmentShader:'#include <packing>\nuniform sampler2D tDiffuse;uniform sampler2D tDepth;uniform vec2 res;uniform float near;uniform float far;uniform float strength;uniform float time;uniform float uRain;uniform float uAberr;uniform float uHurt;uniform float uBlind;uniform float uDanger;uniform float uPulse;uniform float uGrain;uniform float uGrade;varying vec2 vUv;float vz(vec2 uv){float d=texture2D(tDepth,uv).r;return -perspectiveDepthToViewZ(d,near,far);}void main(){vec4 col=texture2D(tDiffuse,vUv);if(uAberr>0.0001){vec2 dir=(vUv-0.5)*uAberr;col.r=texture2D(tDiffuse,vUv+dir).r;col.b=texture2D(tDiffuse,vUv-dir).b;}float zc=vz(vUv);vec2 px=1.0/res;float zl=vz(vUv-vec2(px.x,0.)),zr=vz(vUv+vec2(px.x,0.)),zu=vz(vUv+vec2(0.,px.y)),zd=vz(vUv-vec2(0.,px.y));float e=(abs(zc-zl)+abs(zc-zr)+abs(zc-zu)+abs(zc-zd))/max(zc,0.2);float edge=smoothstep(0.035,0.09,e);if(zc>far*0.95)edge=0.0;float fade=1.0-smoothstep(25.0,60.0,zc);col.rgb*=1.0-edge*strength*fade;float g=fract(sin(dot(vUv*res+time,vec2(12.9898,78.233)))*43758.5453);col.rgb+=(g-0.5)*uGrain;if(uRain>0.0){float cx=vUv.x*160.0;float sp=fract(sin(floor(cx)*91.7)*43758.5453);float y=fract(vUv.y*2.5+time*(2.0+sp*1.5)+sp*7.0);float w=1.0-smoothstep(0.0,0.22,abs(fract(cx)-0.5));float st=smoothstep(0.86,1.0,y)*w*step(0.72,sp);col.rgb+=st*uRain*0.22;}float vig=length(vUv-0.5);col.rgb*=1.0-uHurt*smoothstep(0.25,0.75,vig);col.rgb=mix(col.rgb,vec3(dot(col.rgb,vec3(0.3,0.59,0.11))),uHurt*0.55);col.rgb*=1.0-uBlind*smoothstep(0.1,0.6,vig);float dv=uDanger*(0.42+0.14*uPulse);col.rgb*=1.0-dv*smoothstep(0.26,0.85,vig);float lum=dot(col.rgb,vec3(0.3,0.59,0.11));col.rgb=mix(col.rgb,col.rgb*vec3(0.92,1.0,1.08),uGrade*(1.0-smoothstep(0.15,0.65,lum)));col.rgb=mix(col.rgb,col.rgb*vec3(1.06,1.0,0.94),uGrade*smoothstep(0.55,1.0,lum));gl_FragColor=col;}'};
function attachComposer(){if(!THREE.EffectComposer||!G.scene)return;try{const w=innerWidth,h=innerHeight;const pr=G.ren.getPixelRatio();const rt=new THREE.WebGLRenderTarget(w*pr,h*pr,{minFilter:THREE.LinearFilter,magFilter:THREE.LinearFilter,format:THREE.RGBAFormat});rt.depthTexture=new THREE.DepthTexture(w*pr,h*pr);rt.depthTexture.type=THREE.UnsignedIntType;
  const comp=new THREE.EffectComposer(G.ren,rt);comp.renderTarget1.depthTexture=new THREE.DepthTexture(w*pr,h*pr);comp.renderTarget1.depthTexture.type=THREE.UnsignedIntType;comp.addPass(new THREE.RenderPass(G.scene,G.cam));
  const edge=new THREE.ShaderPass(EDGE_SHADER);edge.uniforms.tDepth.value=rt.depthTexture;edge.uniforms.res.value.set(w*pr,h*pr);edge.uniforms.near.value=G.cam.near;edge.uniforms.far.value=G.cam.far;edge.material.depthWrite=false;edge.material.depthTest=false;comp.addPass(edge);G.edgePass=edge;
  const bloom=new THREE.UnrealBloomPass(new THREE.Vector2(w,h),0.5,0.4,0.86);comp.addPass(bloom);
  const gam=new THREE.ShaderPass(THREE.GammaCorrectionShader);gam.material.depthWrite=false;gam.material.depthTest=false;comp.addPass(gam);
  if(THREE.FXAAShader){const fx=new THREE.ShaderPass(THREE.FXAAShader);fx.uniforms.resolution.value.set(1/(w*pr),1/(h*pr));fx.material.depthWrite=false;fx.material.depthTest=false;comp.addPass(fx);G.fxaa=fx;}
  comp.setSize(w,h);G.composer=comp;G.bloom=bloom;}catch(e){console.warn('composer',e);G.composer=null;}}
let _glowTex=null;function glowTex(){if(_glowTex)return _glowTex;const c=document.createElement('canvas');c.width=c.height=128;const x=c.getContext('2d');const g=x.createRadialGradient(64,64,2,64,64,64);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(0.25,'rgba(255,255,255,0.45)');g.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=g;x.fillRect(0,0,128,128);_glowTex=new THREE.CanvasTexture(c);return _glowTex;}
function glowSprite(color,scale,opacity){const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:glowTex(),color,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,opacity:opacity||0.4}));sp.scale.set(scale,scale*0.6,1);return sp;}
function surfaceAt(k,x,z){const c=cellAt(G.map,k,x,z);if(c===T_YARD)return 'gravel';if(c===T_STAIR)return 'metal';if(G.map.loc.wet)return 'wet';return 'concrete';}
const _signTex={};
function stairSign(txt,color,x,y,z){let tex=_signTex[txt];if(!tex){const c=document.createElement('canvas');c.width=256;c.height=96;const g=c.getContext('2d');g.fillStyle='rgba(6,10,8,0.85)';g.fillRect(4,10,248,76);g.strokeStyle=color;g.lineWidth=4;g.strokeRect(4,10,248,76);g.font='bold 44px Segoe UI, sans-serif';g.textAlign='center';g.fillStyle=color;g.shadowColor=color;g.shadowBlur=14;g.fillText(txt,128,64);tex=new THREE.CanvasTexture(c);_signTex[txt]=tex;}
  const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthWrite:false,fog:false}));sp.scale.set(1.9,0.72,1);sp.position.set(x,y,z);sp.renderOrder=50;sp.userData.own=true;return sp;}
function clearScene(){G.ghosts=[];if(G.scene){G.scene.traverse(o=>{if(o.geometry&&o.userData.own)o.geometry.dispose();});}G.composer=null;G.lightning=null;G.crLights=[];G.scene=new THREE.Scene();G.objs=[];G.objById={};G.creatures=[];G.doors={};G.lights=[];G.lightPool=[];G.props=[];G.docs=[];G.avatars={};G.pings=[];G.markers=[];G.flareObjs=[];G.lamps={};G.elevator=null;}
function buildWorld(map){
  clearScene();const sc=G.scene,pal=map.loc.pal;
  const fogC=new THREE.Color(pal.ceil).multiplyScalar(0.3).lerp(new THREE.Color(0x04070c),0.55);sc.background=fogC;sc.fog=new THREE.FogExp2(fogC.getHex(),(S.set.gfx>=1?0.026:0.038)*(map.loc.fog||1));
  const dk=map.loc.dark?0.45:1;sc.add(new THREE.AmbientLight(0x8090a8,0.16*dk));const hemi=new THREE.HemisphereLight(0x223040,0x120c08,0.22*dk);sc.add(hemi);G.hemi=hemi;
  const ltex=map.loc.tex||{};const wallTex=mkTex(ltex.wall||'panel',hex(pal.wall)),floorTex=mkTex(ltex.floor||'tiles',hex(pal.floor)),ceilTex=mkTex(ltex.ceil||'concrete',hex(pal.ceil)),yardTex=mkTex('concrete','#1a1c1e');
  wallTex.repeat.set(1,1);floorTex.repeat.set(1,1);
  const wallMat=new THREE.MeshStandardMaterial({map:wallTex,bumpMap:wallTex,bumpScale:0.03,roughness:0.86,metalness:0.04,side:THREE.DoubleSide}),floorMat=new THREE.MeshStandardMaterial({map:floorTex,bumpMap:floorTex,bumpScale:0.02,roughness:map.loc.wet?0.3:0.85,metalness:map.loc.wet?0.18:0}),ceilMat=new THREE.MeshStandardMaterial({map:ceilTex,bumpMap:ceilTex,bumpScale:0.02,roughness:1,side:THREE.DoubleSide}),trimMat=new THREE.MeshStandardMaterial({color:pal.trim,roughness:0.6,metalness:0.3});
  floorMat.side=THREE.DoubleSide;ceilMat.side=THREE.DoubleSide;G.mats={wallMat,floorMat,ceilMat,trimMat};enhanceSurface(floorMat,!!map.loc.wet);enhanceSurface(wallMat,false);
  const wallGeo=new THREE.BoxGeometry(1,WALL_H,0.24),tileGeo=new THREE.BoxGeometry(CELL,0.12,CELL),trimGeo=new THREE.BoxGeometry(1,0.12,0.3);
  const m4=new THREE.Matrix4(),q=new THREE.Quaternion(),v3=new THREE.Vector3(),s3=new THREE.Vector3(1,1,1),e=new THREE.Euler();
  for(let k=0;k<map.L;k++){const lay=map.layers[k],y=layerY(k);const grp=new THREE.Group();grp.name='layer'+k;sc.add(grp);lay.grp=grp;
    const walls=lay.walls.filter(w=>!w.win);
    const wm=new THREE.InstancedMesh(wallGeo,wallMat,walls.length);wm.castShadow=true;wm.receiveShadow=true;
    const tm=new THREE.InstancedMesh(trimGeo,trimMat,walls.length);
    walls.forEach((w,i)=>{v3.set(w.x,y+WALL_H/2,w.z);e.set(0,w.rot===1?Math.PI/2:0,0);q.setFromEuler(e);s3.set(w.len,1,1);m4.compose(v3,q,s3);wm.setMatrixAt(i,m4);v3.y=y+0.06;m4.compose(v3,q,s3);tm.setMatrixAt(i,m4);});
    grp.add(wm);grp.add(tm);
    const fl=[],ce=[];
    for(let z=0;z<map.H;z++)for(let x=0;x<map.W;x++){const c=lay.cells[z*map.W+x];if(c===T_VOID||c===T_STAIR)continue;if(c===T_YARD)continue;fl.push([x,z]);if(c!==T_ELEV)ce.push([x,z]);}
    const fm=new THREE.InstancedMesh(tileGeo,floorMat,fl.length);fm.receiveShadow=true;fl.forEach((c,i)=>{v3.set((c[0]+0.5)*CELL,y-0.06,(c[1]+0.5)*CELL);q.identity();s3.set(1,1,1);m4.compose(v3,q,s3);fm.setMatrixAt(i,m4);});grp.add(fm);
    if(lay.guide&&lay.guide.length>1){const gcol=[0x7ddc7d,0xffd27a,0x8fb6ff,0xff8fb0,0xc8ff8f][k%5];const gmat=new THREE.MeshBasicMaterial({color:gcol,transparent:true,opacity:0.3,depthWrite:false});const gg=lay.guide;for(let i=0;i<gg.length-1;i++){const a=gg[i],b=gg[i+1];const dx=b.x-a.x,dz=b.z-a.z;const len=Math.hypot(dx,dz);if(len<0.05)continue;const sm=new THREE.Mesh(new THREE.BoxGeometry(0.2,0.012,len+0.2),gmat);sm.position.set((a.x+b.x)/2,y+0.006,(a.z+b.z)/2);sm.rotation.y=Math.atan2(dx,dz);sm.renderOrder=2;sm.userData.own=true;grp.add(sm);}}
    for(const r of lay.rooms){if(r.safe)grp.add(stairSign('REST · SAFE ROOM','#7ddc7d',r.cx,y+2.55,r.cz));}
    const cm=new THREE.InstancedMesh(tileGeo,ceilMat,ce.length);ce.forEach((c,i)=>{v3.set((c[0]+0.5)*CELL,y+WALL_H+0.06,(c[1]+0.5)*CELL);q.identity();m4.compose(v3,q,s3);cm.setMatrixAt(i,m4);});grp.add(cm);
    /* windows */
    for(const w of lay.walls.filter(w=>w.win)){const wf=Assets.clone('props','window_frame');wf.position.set(w.x,y,w.z);wf.rotation.y=w.rot===1?Math.PI/2:0;grp.add(wf);
      /* solid dark backing behind glass (the void) */const back=new THREE.Mesh(new THREE.PlaneGeometry(1.4,3.4),new THREE.MeshBasicMaterial({color:0x000000,side:THREE.DoubleSide}));back.position.set(w.x,y+1.7,w.z);back.rotation.y=w.rot===1?Math.PI/2:0;const win=map.windows.find(v=>v.k===k&&Math.abs(v.x-w.x)<0.01&&Math.abs(v.z-w.z)<0.01);if(win){back.position.x+=win.nx*1.1;back.position.z+=win.nz*1.1;}grp.add(back);w.backing=back;}
    /* doors */
    for(const d of lay.doors){if(d.blast)continue;const g=new THREE.Group();const panel=Assets.clone('props','door');g.add(panel);const frame=Assets.clone('props','doorframe');
      if(d.rot===1){g.position.set(d.x,y,d.z-DOOR_W/2+0.05);frame.position.set(d.x,y,d.z-DOOR_W/2+0.05);frame.rotation.y=-Math.PI/2;d.baseRot=-Math.PI/2;}else{g.position.set(d.x-DOOR_W/2+0.05,y,d.z);frame.position.set(d.x-DOOR_W/2+0.05,y,d.z);d.baseRot=0;}
      g.rotation.y=d.baseRot;grp.add(g);grp.add(frame);d.mesh=g;G.doors[d.id]=d;}
    /* elevator cab */
    if(map.elev){const el=Assets.clone('props','elevator');el.position.set(map.elev.wx,y,map.elev.wz);el.rotation.y=Math.PI/2;grp.add(el);}
    /* lamps */
    for(const l of map.lights.filter(l=>l.k===k)){const lm=Assets.clone('props','lamp');lm.position.set(l.x,y+WALL_H,l.z);lm.rotation.y=Math.random()<0.5?0:Math.PI/2;grp.add(lm);let tube=null;lm.traverse(m=>{if(m.isMesh&&m.material&&m.material.name==='p_tube'){m.material=m.material.clone();tube=m.material;}});l.mesh=lm;l.tube=tube;const gs=glowSprite(pal.light,2.6,0.42);gs.position.set(l.x,y+WALL_H-0.35,l.z);grp.add(gs);l.glow=gs;
      const em=Assets.clone('props','lamp_emergency');em.position.set(l.x+0.8,y+WALL_H,l.z);em.visible=false;grp.add(em);l.emesh=em;const eg=glowSprite(0xff2010,1.8,0);eg.position.set(l.x+0.8,y+WALL_H-0.25,l.z);eg.visible=false;grp.add(eg);l.eglow=eg;G.lamps[l.id]=l;G.lights.push(l);}
    /* vents */
    for(const v of map.vents.filter(v=>v.k===k)){const vm=Assets.clone('props','vent');vm.position.set(v.x,y+WALL_H-0.02,v.z);grp.add(vm);v.mesh=vm;}
    /* stairs rails + ramp */
    for(const st of map.stairs.filter(s=>s.k===k)){const len=Math.hypot(3*CELL,LAYER_GAP);const ramp=new THREE.Mesh(new THREE.BoxGeometry(CELL-0.5,0.3,len),floorMat);ramp.receiveShadow=true;ramp.castShadow=true;
      const cx=st.x*CELL+CELL/2+st.dx*CELL,cz=st.z*CELL+CELL/2+st.dz*CELL;ramp.position.set(cx,y-LAYER_GAP/2-0.15,cz);const yaw=Math.atan2(st.dx,st.dz);ramp.rotation.order='YXZ';ramp.rotation.y=yaw;ramp.rotation.x=Math.atan2(LAYER_GAP,3*CELL);sc.add(ramp);sc.add(stairSign('▼ DOWN','#7ddc7d',(st.x-st.dx+0.5)*CELL,y+2.55,(st.z-st.dz+0.5)*CELL));sc.add(stairSign('▲ UP','#ffd27a',(st.x+st.dx*3+0.5)*CELL,layerY(k+1)+2.55,(st.z+st.dz*3+0.5)*CELL));
      for(const s of [-1,1]){const rail=Assets.clone('props','stairs_rail');rail.position.set(cx+Math.cos(yaw)*s*(CELL/2-0.35),y-LAYER_GAP/2+0.1,cz-Math.sin(yaw)*s*(CELL/2-0.35));rail.rotation.order='YXZ';rail.rotation.y=yaw;rail.rotation.x=Math.atan2(LAYER_GAP,3*CELL);sc.add(rail);}
      /* end walls to close the shaft top opening above the lower layer exit */}
    /* props */
    for(const p of map.props.filter(p=>p.k===k)){if(PHYS_PROPS[p.n]){spawnObj({kind:'prop',prop:p.n,x:p.x,z:p.z,k,id:p.id,yaw:p.rot});continue;}const pm=Assets.clone('props',p.n);pm.position.set(p.x,y,p.z);pm.rotation.y=p.rot;grp.add(pm);p.mesh=pm;G.props.push(p);}
    /* docs */
    for(const d of map.docs.filter(d=>d.k===k)){const dm=Assets.clone('loot','map');dm.position.set(d.x,y+0.02,d.z);dm.rotation.y=Math.random()*TAU;dm.scale.set(1.6,1.6,1.6);grp.add(dm);d.mesh=dm;G.docs.push(d);}
  }
  /* yard */
  {const yg=new THREE.Mesh(new THREE.PlaneGeometry(map.W*CELL+80,60),new THREE.MeshStandardMaterial({map:yardTex,roughness:1}));yardTex.repeat.set(20,8);yg.rotation.x=-Math.PI/2;yg.position.set(map.W*CELL/2,-0.02,map.H*CELL+10);yg.receiveShadow=true;sc.add(yg);
    for(const [x,z] of [[map.van.x-9,map.van.z+2],[map.van.x+9,map.van.z+2]]){const lp=Assets.clone('props','lamppost');lp.position.set(x,0,z);sc.add(lp);const pl=new THREE.PointLight(0xffe0b0,1.7,24,2);pl.position.set(x,3.4,z-0.3);sc.add(pl);const lg=glowSprite(0xffe0b0,3.2,0.5);lg.position.set(x,3.42,z-0.2);sc.add(lg);}
    /* roof slab */const roof=new THREE.Mesh(new THREE.BoxGeometry(map.W*CELL,0.4,(map.H-2)*CELL),ceilMat);roof.position.set(map.W*CELL/2,WALL_H+0.35,(map.H-2)*CELL/2);sc.add(roof);
    /* blast door */const bd=Assets.clone('props','blastdoor');bd.position.set(map.exit.x,0,map.exit.z);sc.add(bd);map.exit.mesh=bd;G.doors.exit=map.exit;
    /* hatch */const hm=Assets.clone('props','vent');hm.position.set(map.hatch.x,0.02,map.hatch.z);hm.rotation.x=Math.PI;sc.add(hm);map.hatch.mesh=hm;
    /* generator */const gm=Assets.clone('props','generator');gm.position.set(map.gen.x,layerY(map.gen.k),map.gen.z);gm.rotation.y=Math.PI/2;map.layers[map.gen.k].grp.add(gm);map.gen.mesh=gm;map.layers[map.gen.k].addCol({x0:map.gen.x-0.45,x1:map.gen.x+0.45,z0:map.gen.z-0.75,z1:map.gen.z+0.75,prop:{n:'generator'},h:1.1});
    /* van */const van=Assets.clone('van','Van');van.position.set(map.van.x,0,map.van.z);van.scale.setScalar(1.35);sc.add(van);G.vanDoors=[];for(const dn of ['Door_L','Door_R']){const dd=Assets.clone('van',dn);const src=Assets.node('van',dn);dd.position.copy(src.position);const q=src.quaternion;let oy=2*Math.atan2(q.y,q.w);if(oy>Math.PI)oy-=2*Math.PI;if(oy<-Math.PI)oy+=2*Math.PI;dd.userData.openY=oy;dd.rotation.set(0,vanLocked()?0:oy,0);van.add(dd);G.vanDoors.push(dd);}G.van=van;
    const vl=new THREE.PointLight(0xffd9a0,1.8,12,2);vl.position.set(map.van.x,2.9,map.van.z-1.6);sc.add(vl);const vg=glowSprite(0xffd9a0,2.6,0.35);vg.position.set(map.van.x,3.05,map.van.z-1.6);sc.add(vg);
    G.vanZone={x0:map.van.x-1.35,x1:map.van.x+1.35,z0:map.van.z-4.6,z1:map.van.z+0.75,y0:0.3,y1:3.4};
    const lay0=map.layers[0];lay0.addCol({x0:map.van.x-1.65,x1:map.van.x-1.42,z0:map.van.z-3.95,z1:map.van.z+3.95,wall:true});lay0.addCol({x0:map.van.x+1.42,x1:map.van.x+1.65,z0:map.van.z-3.95,z1:map.van.z+3.95,wall:true});lay0.addCol({x0:map.van.x-1.6,x1:map.van.x+1.6,z0:map.van.z+0.75,z1:map.van.z+3.95,wall:true});
    lay0.addCol({x0:map.van.x-1.42,x1:map.van.x+1.42,z0:map.van.z-3.95,z1:map.van.z+0.75,prop:{n:'vanfloor'},h:0.67,step:true});lay0.addCol({x0:map.van.x-1.5,x1:map.van.x+1.5,z0:map.van.z-4.15,z1:map.van.z-3.9,wall:true,vanLock:true});
    /* rain */if(S.set.gfx>=1){const n=900,pos=new Float32Array(n*3);for(let i=0;i<n;i++){pos[i*3]=map.van.x-20+Math.random()*40;pos[i*3+1]=Math.random()*10;pos[i*3+2]=map.van.z-14+Math.random()*30;}const rg=new THREE.BufferGeometry();rg.setAttribute('position',new THREE.BufferAttribute(pos,3));G.rain=new THREE.Points(rg,new THREE.PointsMaterial({color:0x8899aa,size:0.06,transparent:true,opacity:0.5}));sc.add(G.rain);}
  }
  /* dust motes */
  {const n=400,pos=new Float32Array(n*3);for(let i=0;i<n;i++){pos[i*3]=Math.random()*10-5;pos[i*3+1]=Math.random()*3;pos[i*3+2]=Math.random()*10-5;}const dg=new THREE.BufferGeometry();dg.setAttribute('position',new THREE.BufferAttribute(pos,3));G.dust=new THREE.Points(dg,new THREE.PointsMaterial({color:0xc0b090,size:0.03,transparent:true,opacity:0.35}));sc.add(G.dust);}
  /* light pool */
  for(let i=0;i<(S.set.gfx>=2?12:7);i++){const pl=new THREE.PointLight(pal.light,0,16,2);sc.add(pl);G.lightPool.push(pl);}
  G.shadowLamp=new THREE.PointLight(pal.light,0,16,2);G.shadowLamp.castShadow=S.set.gfx>=3;G.shadowLamp.shadow.mapSize.set(512,512);G.shadowLamp.shadow.bias=-0.004;sc.add(G.shadowLamp);
  G.crLights=[];for(let i=0;i<4;i++){const pl=new THREE.PointLight(0xffffff,0,6,2);sc.add(pl);G.crLights.push(pl);}G.glowPool=[];for(let i=0;i<(S.set.gfx>=2?6:4);i++){const pl=new THREE.PointLight(0xffffff,0,4,2);sc.add(pl);G.glowPool.push(pl);}
  G.lightning=new THREE.DirectionalLight(0xdde8ff,0);G.lightning.position.set(30,60,10);sc.add(G.lightning);G.lightningT=8+Math.random()*20;G.flashSeq=0;
  /* flashlight */
  const fl=new THREE.SpotLight(0xfff2d8,0,26,0.45,0.65,1.6);fl.castShadow=S.set.gfx>=2;fl.shadow.mapSize.set(S.set.gfx>=3?2048:1024,S.set.gfx>=3?2048:1024);fl.shadow.bias=-0.002;fl.position.set(0.18,-0.12,0.1);fl.target.position.set(0.05,-0.15,-4);G.cam.add(fl);G.cam.add(fl.target);sc.add(G.cam);G.flash=fl;
  if(!G.vm){const vm=new THREE.Group();const glove=new THREE.MeshStandardMaterial({color:0x2a2825,roughness:0.9});const met=new THREE.MeshStandardMaterial({color:0x5a5c60,roughness:0.4,metalness:0.7});const suit=new THREE.MeshStandardMaterial({color:COS.color[S.cos.color||0],roughness:0.85});
    const add=(g,m,p,r)=>{const o=new THREE.Mesh(g,m);o.position.set(p[0],p[1],p[2]);if(r)o.rotation.set(r[0],r[1],r[2]);vm.add(o);return o;};
    add(new THREE.BoxGeometry(0.09,0.1,0.15),glove,[0,0,0]);for(let i=0;i<4;i++)add(new THREE.BoxGeometry(0.018,0.065,0.022),glove,[-0.033+i*0.022,-0.015,-0.075],[-1.25,0,0]);add(new THREE.BoxGeometry(0.02,0.06,0.02),glove,[0.052,0.015,-0.02],[0,0,-0.7]);
    add(new THREE.BoxGeometry(0.07,0.03,0.05),new THREE.MeshStandardMaterial({color:0x7a5c25,roughness:0.9}),[0,0.05,0.02]);
    add(new THREE.CylinderGeometry(0.06,0.066,0.1,8),suit,[0,-0.01,0.12],[Math.PI/2,0,0]);add(new THREE.CylinderGeometry(0.05,0.062,0.34,8),suit,[0,-0.01,0.33],[Math.PI/2,0,0]);add(new THREE.CylinderGeometry(0.064,0.064,0.02,8),new THREE.MeshStandardMaterial({color:0xbdbd9a,emissive:0x444430}),[0,-0.01,0.2],[Math.PI/2,0,0]);
    add(new THREE.CylinderGeometry(0.03,0.03,0.24,10),met,[0,0.005,-0.05],[Math.PI/2,0,0]);add(new THREE.CylinderGeometry(0.046,0.032,0.06,10),met,[0,0.005,-0.2],[Math.PI/2,0,0]);for(let i=0;i<3;i++)add(new THREE.CylinderGeometry(0.032,0.032,0.012,10),glove,[0,0.005,0.0+i*0.035],[Math.PI/2,0,0]);
    const lensM=new THREE.MeshBasicMaterial({color:0xfff2c8});add(new THREE.CircleGeometry(0.04,14),lensM,[0,0.005,-0.231],[0,Math.PI,0]);G.vmLens=lensM;
    vm.position.set(0.3,-0.24,-0.42);vm.rotation.set(0.06,-0.18,0.12);vm.traverse(m=>{if(m.isMesh){m.castShadow=false;m.receiveShadow=false;m.frustumCulled=false;}});G.cam.add(vm);G.vm=vm;}G.vm.visible=true;
  if(!G.beam){const bg=new THREE.ConeGeometry(1.5,7.5,24,1,true);bg.translate(0,-3.75,0);bg.rotateX(Math.PI/2);G.beam=new THREE.Mesh(bg,new THREE.MeshBasicMaterial({color:0xfff0c0,transparent:true,opacity:0.035,blending:THREE.AdditiveBlending,depthWrite:false,side:THREE.DoubleSide,fog:false}));G.beam.position.set(0.18,-0.14,0.1);G.beam.rotation.y=0.012;G.cam.add(G.beam);G.fill=new THREE.PointLight(0xffe8d0,0.2,7,2);G.cam.add(G.fill);}G.beam.visible=true;
  /* items */
  for(const it of map.items)spawnObj({kind:'item',tpl:it.tpl,value:it.value,x:it.x,z:it.z,k:it.k,id:it.id,yaw:it.rot});
  /* objective placeables */
  placeObjective(map);attachComposer();
}
function placeObjective(map){const o=G.mission.objective,dr=map.deepRoom,y=layerY(dr.k),grp=map.layers[dr.k].grp;
  if(o.id==='researcher'){const c=Assets.clone('props','corpse');c.position.set(dr.cx,y,dr.cz);c.rotation.y=Math.random()*TAU;grp.add(c);spawnObj({kind:'item',tpl:-1,special:'tag',value:0,x:dr.cx+0.6,z:dr.cz+0.4,k:dr.k,id:'objtag'});}
  else if(o.id==='drive'){const t=Assets.clone('props','terminal');t.position.set(dr.cx,y,dr.cz+1);grp.add(t);map.specials.terminal={x:dr.cx,z:dr.cz+1,k:dr.k,prog:0,done:false};map.layers[dr.k].addCol({x0:dr.cx-0.3,x1:dr.cx+0.3,z0:dr.cz+0.75,z1:dr.cz+1.25,prop:{n:'terminal'},h:1.2});}
  else if(o.id==='samples'){const s=Assets.clone('props','sample_station');s.position.set(dr.cx,y,dr.cz);grp.add(s);for(let i=0;i<3;i++){const r=pick(map.layers[Math.max(0,dr.k-Math.floor(Math.random()*2))].rooms);spawnObj({kind:'item',tpl:1,value:300,x:r.cx+Math.random()*2-1,z:r.cz+Math.random()*2-1,k:r.k,id:'sample'+i});}}
  else if(o.id==='beacon'){const b=Assets.clone('props','beacon');b.position.set(dr.cx,y,dr.cz);grp.add(b);map.specials.beacon={x:dr.cx,z:dr.cz,k:dr.k,prog:0,done:false};}
  else if(o.id==='artifact'){spawnObj({kind:'item',tpl:o.tpl,value:o.value,x:dr.cx,z:dr.cz,k:dr.k,id:'artifact'});}
  else if(o.id==='signal')placeSignal(map);
}
function placeSignal(map){const rng=mulberry((G.mission.seed^0x51)>>>0);const sg={gens:[],order:[],next:0,term:null,done:false,known:false};const nk=Math.min(4,map.L);
  for(let k=0;k<nk;k++){const all=map.layers[k].rooms;const rooms=k===0?all.slice(1):all;const r=rooms[Math.floor(rng()*rooms.length)]||all[0];const y=layerY(k);const g=Assets.clone('props','generator');g.position.set(r.cx+1.2,y,r.cz);g.rotation.y=rng()*TAU;map.layers[k].grp.add(g);map.layers[k].addCol({x0:r.cx+0.6,x1:r.cx+1.8,z0:r.cz-0.6,z1:r.cz+0.6,prop:{n:'generator'},h:1.4});
    const lamp=new THREE.PointLight(0xff3020,1.2,7,2);lamp.position.set(r.cx+1.2,y+1.2,r.cz);map.layers[k].grp.add(lamp);sg.gens.push({i:k,x:r.cx+1.2,z:r.cz,k,on:true,mesh:g,lamp});}
  const order=sg.gens.map((g,i)=>i);for(let i=order.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[order[i],order[j]]=[order[j],order[i]];}sg.order=order;
  const sr=map.layers[0].rooms[0];const t=Assets.clone('props','terminal');t.position.set(sr.cx-1.2,layerY(0),sr.cz+0.5);map.layers[0].grp.add(t);map.layers[0].addCol({x0:sr.cx-1.5,x1:sr.cx-0.9,z0:sr.cz+0.25,z1:sr.cz+0.75,prop:{n:'terminal'},h:1.2});sg.term={x:sr.cx-1.2,z:sr.cz+0.5,k:0,read:false};
  map.specials.sig=sg;}
function sigFloor(k){return k===0?'Ground':'B'+k;}
function sigReveal(){const sg=G.map.specials&&G.map.specials.sig;if(!sg)return;sg.known=true;if(sg.term)sg.term.read=true;const names=sg.order.map(i=>sigFloor(sg.gens[i].k));toast('🖥 TERMINAL — shutdown order: '+names.join(' → '),'big');Aud.ui('ok');updateObjHud();}
function doSigTerm(){sigReveal();if(MP.on){if(mpHost())bcast({t:'ev',k:'sigorder'});else sendAct({k:'sigterm'});}}
function doSigGen(g){if(mpHost())sigGenHost(g.i,P.id);else sendAct({k:'siggen',i:g.i});}
function sigApply(gensOn,next,done){const sg=G.map.specials&&G.map.specials.sig;if(!sg)return;sg.gens.forEach((g,i)=>{const on=!!gensOn[i];if(g.on!==on){g.on=on;if(g.lamp)g.lamp.color.setHex(on?0xff3020:0x203020);if(g.lamp)g.lamp.intensity=on?1.2:0.35;}});sg.next=next;sg.done=!!done;updateObjHud();}
/* ================= PHYSICS OBJECTS ================= */
function spawnObj(d){const o={id:d.id||('o'+Math.random().toString(36).slice(2,8)),kind:d.kind,tpl:d.tpl,special:d.special,prop:d.prop,value:d.value||0,p:new THREE.Vector3(d.x,d.y!==undefined?d.y:groundY(G.map,d.k,d.x,d.z),d.z),v:new THREE.Vector3(),k:d.k,yaw:d.yaw||0,spin:0,held:null,holders:[],onGround:false,sleep:false,broken:false,inVan:false,net:null,lastImpact:0,vanT:0};
  let mname='generic',lib='loot';
  if(d.kind==='prop'){mname=d.prop;lib='props';const pp=PHYS_PROPS[d.prop];o.r=pp.r;o.h=pp.h;o.mass=pp.mass;o.noise=pp.noise;o.sz=2;}
  else if(d.special==='tag'){mname='tag';o.r=0.1;o.h=0.1;o.mass=0.1;o.sz=0;o.name='Researcher\'s Tag';o.ic='🏷';}
  else if(d.special==='flare'){mname='vial';o.r=0.05;o.h=0.12;o.mass=0.3;o.sz=0;}
  else{const t=ITEMS[d.tpl];mname=LOOT_MESH[d.tpl]||'generic';const s=Assets.size('loot',mname);o.r=Math.max(0.08,s.r);o.h=Math.max(0.08,s.h);o.mass=t.w*0.55;o.sz=t.sz;o.frag=t.frag||0;o.name=t.n;o.ic=t.ic;o.curse=t.curse;o.rar=t.r;}
  const m=Assets.clone(lib,mname);o.mesh=new THREE.Group();o.mesh.add(m);if(d.special==='flare'){o.mesh.add(new THREE.PointLight(0xff4020,2,9,2));m.traverse(x=>{if(x.isMesh)x.material=new THREE.MeshBasicMaterial({color:0xff3010});});}
  if(d.kind==='item'&&ITEMS[d.tpl]&&(ITEMS[d.tpl].glow||ITEMS[d.tpl].pulse)){const c=ITEMS[d.tpl].c;o.glowC=c;o.glowOn=true;o.glowPulse=!!ITEMS[d.tpl].pulse;}
  o.mesh.position.copy(o.p);o.mesh.rotation.y=o.yaw;G.scene.add(o.mesh);G.objs.push(o);G.objById[o.id]=o;return o;}
function removeObj(o){if(!o)return;G.scene.remove(o.mesh);G.objs=G.objs.filter(x=>x!==o);delete G.objById[o.id];}
function vanLocked(){const M=G.mission;return !!(M&&!M.sandbox&&!M.tutorial&&M.time<(M.vanLockT||0));}
function inVanZone(p){const z=G.vanZone;if(vanLocked())return false;return z&&p.x>z.x0&&p.x<z.x1&&p.z>z.z0&&p.z<z.z1&&p.y>z.y0-0.4&&p.y<z.y1;}
function objGround(o){/* floor incl. low props */let g=groundY(G.map,o.k,o.p.x,o.p.z);nearCols(G.map,o.k,o.p.x,o.p.z,_cols);for(const b of _cols){if(!b.prop)continue;if(o.p.x>b.x0-o.r*0.5&&o.p.x<b.x1+o.r*0.5&&o.p.z>b.z0-o.r*0.5&&o.p.z<b.z1+o.r*0.5){const top=layerY(o.k)+b.h;if(o.p.y>=top-0.35&&top>g)g=top;}}return g;}
const _tmpV=new THREE.Vector3();
function stepObj(o,dt){
  if(o.held!==null||o.holders.length||o.carrier)return;
  if(o.sleep)return;
  const grav=G.gravity;o.v.y-=grav*dt;
  o.p.x+=o.v.x*dt;o.p.z+=o.v.z*dt;o.p.y+=o.v.y*dt;
  /* layer by height */const g=objGround(o);
  if(o.p.y<=g){const imp=-o.v.y;o.p.y=g;
    if(imp>2.5){const vol=clamp(imp/9,0.15,1);o.v.y=imp*0.28;o.v.x*=0.6;o.v.z*=0.6;o.spin*=0.5;if(G.t-o.lastImpact>0.15){o.lastImpact=G.t;Aud.impact(vol*(o.noise||0.6),o.p,o.prop==='barrel'?'metal':null);emitNoise(o.p,o.k,vol*(o.noise||0.6),'impact');
      if(o.frag&&!o.broken){const recent=G.t-(o.thrownAt||0)<4;const th=(recent&&o.harsh?[99,5,4,3]:recent?[99,12,10,8]:[99,9.5,7.5,5.5])[o.frag]||99;if(imp>th)breakObj(o);}}}
    else{o.v.y=0;o.onGround=true;const f=Math.pow(0.05,dt);o.v.x*=f;o.v.z*=f;o.spin*=f;if(Math.abs(o.v.x)+Math.abs(o.v.z)<0.05){o.v.set(0,0,0);o.sleep=true;}}
  }else o.onGround=false;
  const p2={x:o.p.x,z:o.p.z};const hit=collideCircle(G.map,o.k,p2,o.r,o.p.y,o.h);
  if(hit){const sp=Math.hypot(o.v.x,o.v.z);if(sp>2.5&&G.t-o.lastImpact>0.15){o.lastImpact=G.t;Aud.impact(clamp(sp/9,0.15,0.8)*(o.noise||0.6),o.p,o.prop==='barrel'?'metal':null);emitNoise(o.p,o.k,clamp(sp/9,0.15,0.9)*(o.noise||0.6),'impact');if(o.frag&&!o.broken){const recent=G.t-(o.thrownAt||0)<4;if(sp>((recent&&o.harsh?[99,6,5,3.8]:recent?[99,13,11,9]:[99,10.5,8.5,6.5])[o.frag]||99))breakObj(o);}}
    /* reflect */const nx=p2.x-o.p.x,nz=p2.z-o.p.z;const nl=Math.hypot(nx,nz);if(nl>1e-5){const dot=(o.v.x*nx+o.v.z*nz)/nl;if(dot<0){o.v.x-=nx/nl*dot*1.4;o.v.z-=nz/nl*dot*1.4;}}o.p.x=p2.x;o.p.z=p2.z;}
  o.yaw+=o.spin*dt;
  /* layer tracking on ramps / falls */o.k=clamp(Math.round(-(o.p.y)/LAYER_GAP+0.35-0.35),0,G.map.L-1);if(o.p.y<layerY(G.map.L-1)-2){o.p.y=layerY(G.map.L-1);o.v.set(0,0,0);}
}
function stepObjPairs(){const a=G.objs;for(let i=0;i<a.length;i++){const o=a[i];if(o.sleep||o.held!==null)continue;for(let j=0;j<a.length;j++){if(i===j)continue;const q=a[j];if(q.k!==o.k||q.held!==null)continue;const dx=q.p.x-o.p.x,dz=q.p.z-o.p.z,rr=o.r+q.r;if(Math.abs(dx)>rr||Math.abs(dz)>rr)continue;if(Math.abs(q.p.y-o.p.y)>Math.max(o.h,q.h))continue;const d=Math.hypot(dx,dz);if(d<rr&&d>1e-4){const push=(rr-d)*0.5;const nx=dx/d,nz=dz/d;const mo=o.mass/(o.mass+q.mass);o.p.x-=nx*push*(1-mo);o.p.z-=nz*push*(1-mo);q.p.x+=nx*push*mo;q.p.z+=nz*push*mo;q.sleep=false;const sp=Math.hypot(o.v.x,o.v.z);if(sp>2){q.v.x+=nx*sp*0.4*(1-mo);q.v.z+=nz*sp*0.4*(1-mo);o.v.x*=0.6;o.v.z*=0.6;if(q.kind==='prop'||sp>4){Aud.impact(0.3,q.p);}}}}}}
function breakObj(o){if(o.value>0&&o.k===P.k&&!o.broken&&dist2(o.p.x,o.p.z,P.pos.x,P.pos.z)<9){floatText('BROKEN  -'+fmt(o.value)+' cr','red');G.fx.shake+=0.15;}if(o.broken)return;o.broken=true;const lost=o.value*0.85;o.value=Math.round(o.value*0.15);Aud.shatter(o.p);emitNoise(o.p,o.k,1.0,'break');o.mesh.traverse(m=>{if(m.isMesh){m.material=new THREE.MeshStandardMaterial({color:0x2a2a2a,roughness:1});}});o.mesh.scale.set(1,0.35,1);o.glowOn=false;
  const who=o.lastHolder!==undefined&&o.lastHolder!==null?nameOf(o.lastHolder):'someone';toast('💥 '+(o.name||'Something')+' broke! -'+fmt(lost)+' cr ('+who+')');G.mission.stats.broken++;G.mission.brokenValue+=lost;if(o.lastHolder!==undefined&&o.lastHolder!==null)pstat(o.lastHolder,'broke',lost);if(lost>1500)ach('broke');if(mpHost())bcast({t:'ev',k:'break',id:o.id});}
function updateObjMeshes(dt){for(const o of G.objs){if(o.held!==null||o.holders.length){/* holder-driven */}
  else if(!mpHost()&&o.net&&MP.on){o.p.lerp(o.net.p,Math.min(1,dt*10));o.yaw=lerp(o.yaw,o.net.yaw,dt*10);if(o.net.k!==undefined)o.k=o.net.k;}
  o.mesh.position.copy(o.p);o.mesh.rotation.y=o.yaw;o.mesh.rotation.z=o.onGround||o.held!==null?0:Math.sin(G.t*6+o.p.x)*0.3;

  const inv=inVanZone(o.p)&&o.k===0;if(inv!==o.inVan){o.inVan=inv;if(inv&&o.kind==='item'&&o.value>0){Aud.ui('cash');toast('📦 '+o.name+' loaded · '+fmt(o.value)+' cr');}updateVanHud();}
}}
function vanValue(){let v=0;for(const o of G.objs)if(o.inVan&&o.kind==='item')v+=o.value;return v;}
/* ================= LOCAL PLAYER ================= */
const P={id:0,pos:new THREE.Vector3(),vel:new THREE.Vector3(),yaw:0,pitch:0,k:0,eye:1.62,crouch:false,sprint:false,onGround:true,stamina:1,hp:100,downed:false,dead:false,bleed:0,noise:0,noiseT:0,flash:true,batt:1,radio:{on:false,ch:1,batt:1},pockets:[],hands:null,carryW:0,stepT:0,bob:0,lastNoise:0,hurtT:0,medkits:0,flares:0,spare:0,talk:false,micLvl:0,darkT:0,inVan:false,mia:false,spectate:null,revT:0,useT:0,useTarget:null,blind:0,slow:0,lookW:false,alone:0,distance:0,lastPos:null,scream:0,curseT:{},adren:1};
const K={};let mouseDX=0,mouseDY=0,throwCharge=0,throwing=false;
function playerReset(){P.pos.set(G.map.spawn.x,0,G.map.spawn.z);P.k=0;P.vel.set(0,0,0);P.yaw=Math.PI;P.pitch=0;P.hp=100;P.downed=false;P.dead=false;P.bleed=0;P.stamina=1;P.batt=1;P.radio={on:false,ch:1,batt:1};P.pockets=[];P.hands=null;P.flash=true;P.mia=false;P.spectate=null;P.medkits=S.up.medkit;P.flares=[0,2,4,6][S.up.flares]+(perk(5)?2:0);P.spare=S.up.batt;P.blind=0;P.slow=0;P.alone=0;P.minHp=101;P.minHpSrc=null;P.deathSrc=null;P.lastHurtSrc=null;P.distance=0;P.lastPos=null;P.scream=0;P.curseT={};P.adren=1;P.darkT=0;P.eye=1.62;
  if(G.mission.weekly==='noflash')P.flash=false;}
function pocketCap(){return ([2,3,4,5][S.up.pack-1]||2)+(perk(4)?1:0);}
function pocketCost(o){return o.sz>=1?2:1;}
function pocketUsed(){let n=0;for(const id of P.pockets){const o=G.objById[id];n+=o?pocketCost(o):1;}return n;}
function canPocket(o){return !!o&&o.sz<=1&&o.kind!=='prop'&&pocketUsed()+pocketCost(o)<=pocketCap();}
function netPocket(o){if(mpHost())bcast({t:'ev',k:'held',id:o.id,pid:P.id,pocket:true});else sendAct({k:'grab',id:o.id,pocket:true});}
function pocketHeld(){if(!P.hands)return false;const o=G.objById[P.hands];if(!canPocket(o)){if(o&&o.sz>=2)toast('Too big for a pocket.');else toast('Pockets full ('+pocketUsed()+'/'+pocketCap()+').');return false;}P.pockets.push(o.id);o.held=P.id;o.mesh.visible=false;P.hands=null;P.grabAnim=0.7;updateInv();invPop(P.pockets.length-1);Aud.ui('click');toast('👝 Pocketed '+(o.name||'item'));netPocket(o);return true;}
function carryWeight(){let w=0;for(const id of P.pockets){const o=G.objById[id];if(o)w+=o.mass;}if(P.hands){const o=G.objById[P.hands];if(o)w+=o.mass;}return w;}
function moveSpeed(){let s=P.crouch?2.1:(P.sprint&&P.stamina>0.02?6.4:4.1);const w=carryWeight();s*=clamp(1-w/140,0.65,1);if(P.hands){const o=G.objById[P.hands];if(o&&o.sz>=2)s*=0.9;if(o&&o.sz>=3)s*=0.72;}if(S.up.armor>=3)s*=0.92;if(P.downed)s=1.1;if(P.slow>0)s*=0.5;if(G.mission.weekly==='heavy')s*=0.85;return s;}
function updatePlayer(dt){
  if(P.dead){updateSpectate(dt);return;}
  const cam=G.cam;
  /* look */const smo=Math.min(0.85,Math.max(0,S.set.smooth||0));P.smDX=(P.smDX||0)*smo+mouseDX*(1-smo);P.smDY=(P.smDY||0)*smo+mouseDY*(1-smo);if(Math.abs(P.smDX)<0.01)P.smDX=0;if(Math.abs(P.smDY)<0.01)P.smDY=0;mouseDX=P.smDX;mouseDY=P.smDY;const mdx=mouseDX,mdy=mouseDY;const sens=S.set.sens*0.0022;P.yaw-=mouseDX*sens;P.pitch-=mouseDY*sens*(S.set.invertY?-1:1);P.pitch=clamp(P.pitch,S.set.tp?-1.15:-1.5,S.set.tp?1.25:1.5);mouseDX=mouseDY=0;P.swayX=lerp(P.swayX||0,clamp(-mdx*0.0012,-0.04,0.04),1-Math.exp(-7*dt));P.swayY=lerp(P.swayY||0,clamp(mdy*0.0009,-0.03,0.03),1-Math.exp(-7*dt));
  /* move input */let ix=0,iz=0;if(held('forward')||K.ArrowUp)iz-=1;if(held('back')||K.ArrowDown)iz+=1;if(held('left')||K.ArrowLeft)ix-=1;if(held('right')||K.ArrowRight)ix+=1;if(GP.mx||GP.my){ix+=GP.mx;iz+=GP.my;}if(TOUCH.mx||TOUCH.my){ix+=TOUCH.mx;iz+=TOUCH.my;}
  const il=Math.hypot(ix,iz);if(il>1){ix/=il;iz/=il;}
  {const sIn=!!(held('sprint')||K.ShiftRight||GP.sprint);if(S.set.sprintToggle){if(sIn&&!P._sHeld)P.sprintT=!P.sprintT;P._sHeld=sIn;if(iz>=0||P.stamina<=0.02)P.sprintT=false;P.sprint=!!P.sprintT&&iz<0&&!P.downed;}else P.sprint=sIn&&iz<0&&!P.downed;}
  const wantCrouch=!!(held('crouch')||K.ControlLeft||GP.crouch);if(S.set.crouchToggle){if(wantCrouch&&!P._cHeld)P.crouch=!P.crouch;P._cHeld=wantCrouch;}else P.crouch=wantCrouch;
  if(P.downed)P.crouch=true;
  const sp=moveSpeed();const sy=Math.sin(P.yaw),cy=Math.cos(P.yaw);
  const wx=(ix*cy+iz*sy)*sp,wz=(-ix*sy+iz*cy)*sp; /* yaw 0 = looking -z */
  const acc=P.onGround?12:3;P.vel.x=lerp(P.vel.x,wx,1-Math.exp(-acc*dt));P.vel.z=lerp(P.vel.z,wz,1-Math.exp(-acc*dt));
  if(P.sprint&&il>0){P.stamina=Math.max(0,P.stamina-dt*0.16*(G.map.loc.cold?1.3:1)/(perk(1)?1.15:1));if(P.stamina<=0)P.sprint=false;}else P.stamina=Math.min(1,P.stamina+dt*(P.crouch?0.18:0.12)*(G.map.loc.cold?0.6:1)*(perk(1)?1.15:1)*(P.inSafe?1.8:1));if(P.inSafe&&P.hp<60&&!P.dead&&!P.downed){P.hp=Math.min(60,P.hp+dt*1.2);}
  if(P.grabbedT&&G.t<P.grabbedT){P.vel.x=0;P.vel.z=0;}
  /* jump: buffered press + coyote time */{const jp=!!(held('jump')||GP.jump);if(jp&&!P._jHeld)P.jumpBuf=0.12;else P.jumpBuf=Math.max(0,(P.jumpBuf||0)-dt);P.coyote=P.onGround?0.1:Math.max(0,(P.coyote||0)-dt);if(P.jumpBuf>0&&P.coyote>0&&!P.downed&&P.stamina>0.05){P.vel.y=Math.sqrt(2*G.gravity*(G.gravity<12?1.6:1.1));P.onGround=false;P.coyote=0;P.jumpBuf=0;P.stamina-=0.06;}P._jHeld=jp;}
  P.vel.y-=G.gravity*dt;
  P.pos.x+=P.vel.x*dt;P.pos.z+=P.vel.z*dt;P.pos.y+=P.vel.y*dt;
  /* ground */let g=groundY(G.map,P.k,P.pos.x,P.pos.z);nearCols(G.map,P.k,P.pos.x,P.pos.z,_cols);for(const b of _cols){if(!b.prop)continue;if(P.pos.x>b.x0-0.1&&P.pos.x<b.x1+0.1&&P.pos.z>b.z0-0.1&&P.pos.z<b.z1+0.1){const top=layerY(P.k)+b.h;if(P.pos.y>=top-0.6&&top>g&&(b.h<=0.6||b.step||P.pos.y>=top-0.2))g=top;}}
  if(P.pos.y<=g){if(P.vel.y<-9){hurt(Math.min(40,(-P.vel.y-9)*5),'fall');}else if(P.vel.y<-4){Aud.drop(0.3,null);P.landT=0.3;G.fx.shake+=0.18;}P.pos.y=g;P.vel.y=0;P.onGround=true;}else P.onGround=false;
  /* walls */const p2={x:P.pos.x,z:P.pos.z};collideCircle(G.map,P.k,p2,0.36,P.pos.y,1.7);P.pos.x=p2.x;P.pos.z=p2.z;
  /* creature bodies */for(const c of G.creatures){if(!c.visible||c.k!==P.k||c.kind==='hanger'||c.kind==='drifter'||c.kind==='window'||(c.kind==='crawler'&&c.ceiling))continue;const rr=CR_CFG[c.kind].r+0.36;const dx=P.pos.x-c.pos.x,dz=P.pos.z-c.pos.z;const d=Math.hypot(dx,dz);if(d<rr&&d>1e-4){P.pos.x=c.pos.x+dx/d*rr;P.pos.z=c.pos.z+dz/d*rr;}}
  /* ceiling */const ceil=layerY(P.k)+WALL_H-0.1;if(!stairAtPos(G.map,P.k,P.pos.x,P.pos.z)&&cellAt(G.map,P.k,P.pos.x,P.pos.z)!==T_YARD&&P.pos.y+P.eye>ceil){P.pos.y=ceil-P.eye;if(P.vel.y>0)P.vel.y=0;}
  /* layer */const st=stairAtPos(G.map,P.k,P.pos.x,P.pos.z);if(st){const kk=P.pos.y<layerY(st.k)-LAYER_GAP*0.5?st.k+1:st.k;if(kk!==P.k){P.k=kk;onLayerChange();}}else{const kk=clamp(Math.round(-P.pos.y/LAYER_GAP),0,G.map.L-1);if(kk!==P.k&&Math.abs(P.pos.y-layerY(kk))<1.5){P.k=kk;onLayerChange();}}
  /* eye height */const te=P.downed?0.55:(P.crouch?0.95:1.62);P.eye=lerp(P.eye,te,1-Math.exp(-10*dt));
  /* head bob & steps */const hs=Math.hypot(P.vel.x,P.vel.z);if(hs>0.5&&P.onGround){P.bob+=dt*hs*1.6;P.stepT+=dt*hs;const stepLen=P.crouch?1.4:(P.sprint?2.4:1.9);if(P.stepT>stepLen){P.stepT=0;const vol=P.crouch?0.1:(P.sprint?0.5:0.28);const boots=[1,0.6,0.35][S.up.boots-1]||1;Aud.step(vol*0.6,null,P.crouch,surfaceAt(P.k,P.pos.x,P.pos.z));emitNoise(P.pos,P.k,vol*boots*(perk(3)?0.8:1),'step');}}else P.bob=lerp(P.bob,0,dt*5);
  const bobY=Math.sin(P.bob*2)*(P.sprint?0.05:0.025)*(hs>0.5?1:0),bobX=Math.cos(P.bob)*0.02*(hs>0.5?1:0);
  cam.position.set(P.pos.x+bobX*cy,P.pos.y+P.eye+bobY,P.pos.z-bobX*sy);
  cam.rotation.order='YXZ';cam.rotation.set(P.pitch,P.yaw,Math.sin(P.bob)*0.006*(hs>0.5?1:0)+(G.fx.shake>0?Math.sin((G.fx.shT||0)*1.1)*Math.min(1,G.fx.shake)*Math.min(1,G.fx.shake)*0.04*S.set.shake:0));
  /* out of bounds rescue */{const m=G.map;if(m&&!P.dead){const top=layerY(0)+WALL_H+0.6,bot=layerY(m.L-1)-3;if(P.pos.y>top||P.pos.y<bot){if(P.pos.y>top){P.k=0;}P.pos.y=layerY(P.k);P.vel.set(0,0,0);unstick();sysMsg('You left the map — putting you back on the floor.','warn',5);}}}
  /* stuck watchdog */if(!P.stuckRef)P.stuckRef=P.pos.clone();if(il>0&&P.onGround&&!P.dead&&!P.downed&&!(P.grabbedT>G.t)&&!P.inVan){if(P.pos.distanceTo(P.stuckRef)>0.35){P.stuckT=0;P.stuckRef.copy(P.pos);}else{P.stuckT=(P.stuckT||0)+dt;if(P.stuckT>2.2&&!(P.stuckMsgT>G.t-8)){P.stuckMsgT=G.t;sysMsg('You are pushing against something and not moving. Press J (or tap UNSTICK) to hop to the nearest open floor.','warn',7,{label:'UNSTICK',fn:unstick});}}}else{P.stuckT=0;P.stuckRef.copy(P.pos);}
  /* camera juice */if(P.landT>0){P.landT-=dt;cam.position.y-=Math.sin(P.landT/0.3*Math.PI)*0.09;}if(P.kick>0){P.kick-=dt*2.5;cam.rotation.z+=Math.sin(P.kick*9)*0.02*P.kick*S.set.shake;cam.rotation.x-=P.kick*0.02*S.set.shake;}
  const wantFov=S.set.fov+((P.sprint&&il>0&&P.stamina>0.02)?7:0)+(P.grabbedT&&G.t<P.grabbedT?-6:0)+(G.fx.danger||0)*7;if(Math.abs(cam.fov-wantFov)>0.05){cam.fov=lerp(cam.fov,wantFov,1-Math.exp(-6*dt));cam.updateProjectionMatrix();}
  if(G.vm){G.vm.visible=!P.dead;const carry=P.hands&&G.objById[P.hands];P.carryF=lerp(P.carryF||0,carry?1:0,1-Math.exp(-9*dt));P.grabAnim=(P.grabAnim||0)*Math.exp(-5*dt);const dip=Math.sin(Math.min(1,P.grabAnim)*Math.PI)*0.05;const vmx=clamp(0.17*cam.aspect,0.13,0.3);G.vm.position.set(vmx+(P.swayX||0)+P.carryF*0.12,-0.24+bobY*1.6+(P.swayY||0)-(P.crouch?0.03:0)-P.carryF*0.06-dip,-0.42);G.vm.rotation.set(0.06+(P.swayY||0)*1.5,-0.18-(P.swayX||0)*2,0.12-(P.swayX||0)*2);if(G.vmLens)G.vmLens.color.setHex(P.flash&&P.batt>0?0xfff2c8:0x332b20);}
  /* third person: over-the-shoulder spring arm */if(S.set.tp&&!P.dead){const fx=-Math.sin(P.yaw)*Math.cos(P.pitch),fy=Math.sin(P.pitch),fz=-Math.cos(P.yaw)*Math.cos(P.pitch);const rx=Math.cos(P.yaw),rz=-Math.sin(P.yaw);
    /* shoulder: prefer right; swap to left when the right side has no room */const hx=P.pos.x,hz=P.pos.z;const roomR=losClear(G.map,P.k,hx,hz,hx+rx*0.7,hz+rz*0.7),roomL=losClear(G.map,P.k,hx,hz,hx-rx*0.7,hz-rz*0.7);const wantSide=(roomR||!roomL)?1:-1;P.tpSide=P.camSnap?wantSide:lerp(P.tpSide===undefined?1:P.tpSide,wantSide,1-Math.exp(-5*dt));
    /* look-ahead: lead the camera a little into the direction you move */const lvx=P.vel.x,lvz=P.vel.z;const lsp=Math.hypot(lvx,lvz);const lead=lsp>0.5?Math.min(0.35,lsp*0.06):0;const lx=lsp>0.5?lvx/lsp*lead:0,lz=lsp>0.5?lvz/lsp*lead:0;P.tpLx=P.camSnap?lx:lerp(P.tpLx||0,lx,1-Math.exp(-3*dt));P.tpLz=P.camSnap?lz:lerp(P.tpLz||0,lz,1-Math.exp(-3*dt));
    const px=P.pos.x+rx*0.45*P.tpSide+P.tpLx,py=P.pos.y+P.eye+0.15,pz=P.pos.z+rz*0.45*P.tpSide+P.tpLz;
    const want=camArm(P.k,px,pz,fx,fz,2.4);const cur=P.tpDist===undefined||P.camSnap?want:P.tpDist;P.tpDist=want<cur?lerp(cur,want,1-Math.exp(-16*dt)):lerp(cur,want,1-Math.exp(-3.5*dt));
    cam.position.set(px-fx*P.tpDist,py-fy*P.tpDist,pz-fz*P.tpDist);{const cp={x:cam.position.x,z:cam.position.z};collideCircle(G.map,P.k,cp,0.27,cam.position.y-0.3,0.6);cam.position.x=cp.x;cam.position.z=cp.z;}P.camSnap=false;}
  if(G.vm)G.vm.visible=G.vm.visible&&!S.set.tp;updateSelfAvatar(dt);
  if(G.fx.shake>0){const tr=Math.min(1,G.fx.shake);const sh=tr*tr*S.set.shake;G.fx.shT=(G.fx.shT||0)+dt*30;cam.position.y+=Math.sin(G.fx.shT*2.3)*sh*0.07;cam.position.x+=Math.sin(G.fx.shT*1.7)*sh*0.045;cam.position.z+=Math.sin(G.fx.shT*1.3)*sh*0.045;G.fx.shake=Math.max(0,G.fx.shake-dt*1.6);}
  /* distance stat */if(P.lastPos){P.distance+=P.lastPos.distanceTo(P.pos);P.lastPos.copy(P.pos);}else P.lastPos=P.pos.clone();
  /* flashlight */G.flash.intensity=0;if(P.flash&&P.batt>0&&!P.dead){const lv=S.up.flash;const base=[0,0.9,1.25,1.35,1.45,1.9][lv];G.flash.intensity=base*(P.batt<0.12?0.4+Math.random()*0.5:1)*(G.fx.flicker>0?(Math.random()<0.6?0.2:1):1);G.flash.angle=[0,0.4,0.42,0.42,0.6,0.55][lv];G.flash.distance=[0,18,24,26,26,34][lv];G.flash.color.setHex(lv>=5?0xf0f6ff:0xfff0d0);P.batt=Math.max(0,P.batt-dt/([0,240,300,480,480,420][lv])*(G.fx.drain?4:1));P.darkT=0;}else{P.darkT+=dt;if(P.darkT>180)ach('dark');}
  if(G.fx.flicker>0)G.fx.flicker-=dt;
  /* radio battery */if(P.radio.on&&!perk(2))P.radio.batt=Math.max(0,P.radio.batt-dt/600);
  /* bleed-out */if(P.downed){P.bleed-=dt;$('downedT').textContent=MP.on?'Bleeding out in '+Math.ceil(P.bleed)+'s · crawl, talk, wait for a revive':'Adrenaline in '+Math.ceil(P.bleed)+'s · crawl to safety';if(P.bleed<=0){if(MP.on&&Object.keys(MP.players).length>1)die();else{/* solo adrenaline once */if(P.adren>0){P.adren=0;P.downed=false;P.hp=40;$('downed').style.display='none';toast('💉 Adrenaline. One time only.');Aud.sting('revive');}else die();}}}
  /* held item follow */updateHeld(dt);
  /* isolation */let near=false;for(const id in G.avatars){const a=G.avatars[id];if(a.k===P.k&&a.pos.distanceTo(P.pos)<12&&!a.dead)near=true;}if(!near&&MP.on&&Object.keys(MP.players).length>1)P.alone+=dt;
  /* in van */P.inVan=inVanZone(P.pos)&&P.k===0;Aud.setWet(P.k===0&&cellAt(G.map,0,P.pos.x,P.pos.z)===T_YARD?0.07:0.3);
  /* blind */if(P.blind>0){P.blind-=dt;$('vig').style.background='radial-gradient(ellipse at center,rgba(20,30,20,'+(0.9*Math.min(1,P.blind/2))+') 20%,rgba(0,0,0,.95) 100%)';if(P.blind<=0)$('vig').style.background='';}if(P.slow>0)P.slow-=dt;
  /* mic scream detect */if(P.micLvl>0.55&&G.t-P.scream>2){P.scream=G.t;G.mission.stats.screams++;pstat(P.id,'screams',1);}
  /* curses */updateCurses(dt);
}
function onLayerChange(){if(P.k===G.map.L-1&&G.map.L>=3)ach('deep');if(P.k===G.map.L-1)G.mission.reachedDeep=true;Aud.tone(60,0.6,'sine',0.15);}
function updateHeld(dt){if(!P.hands)return;const o=G.objById[P.hands];if(!o){P.hands=null;return;}
  const cam=G.cam;const fwd=new THREE.Vector3(0,0,-1).applyEuler(new THREE.Euler(P.pitch*0.6,P.yaw,0,'YXZ'));const dist=o.sz>=3?1.6:(o.sz>=2?1.1+o.r*0.6:0.75+o.r*0.4);const down=o.sz>=2?0.5:0.35;
  if(S.set.tp)_tmpV.set(P.pos.x,P.pos.y+P.eye,P.pos.z);else _tmpV.copy(cam.position);_tmpV.addScaledVector(fwd,dist);_tmpV.y-=down+ (o.sz>=2?0:0)+(P.crouch?0.1:0);
  if(o.sz>=3&&o.holders.length<2&&MP.on&&Object.keys(MP.players).length>1){/* dragging alone */o.p.lerp(_tmpV,Math.min(1,dt*1.2));}
  else if(o.holders.length>=2){/* two-player carry: midpoint of anchors handled by host snapshots; local anchor sent */o.anchor=_tmpV.clone();if(mpHost())twoCarryUpdate(o,dt);}
  else o.p.lerp(_tmpV,Math.min(1,dt*(o.sz>=2?9:16)));
  /* keep out of walls */const p2={x:o.p.x,z:o.p.z};collideCircle(G.map,P.k,p2,o.r*0.8,o.p.y,o.h);o.p.x=p2.x;o.p.z=p2.z;o.k=P.k;o.yaw=P.yaw;o.v.copy(P.vel);
  /* struggle: heavy items can slip when sprinting/jumping */if(o.sz>=2&&(!P.onGround||(P.sprint&&Math.random()<dt*0.08))){if(Math.random()<dt*0.3){dropHands(true);toast('😬 You lost your grip!');}}
}
function twoCarryUpdate(o,dt){const anchors=[];if(o.holders.includes(P.id)&&o.anchor)anchors.push(o.anchor);for(const id of o.holders){if(id===P.id)continue;const a=G.avatars[id];if(a&&a.anchor)anchors.push(a.anchor);}if(anchors.length){const m=new THREE.Vector3();for(const a of anchors)m.add(a);m.divideScalar(anchors.length);o.p.lerp(m,Math.min(1,dt*6));}}
/* ---- interaction ---- */
const ray=new THREE.Raycaster();
function lookTarget(){/* returns {kind, obj/door/..., dist, label} nearest along view */const cam=G.cam;const fwd=new THREE.Vector3(0,0,-1).applyQuaternion(cam.quaternion);let best=null;
  const consider=(kind,ref,p,r,maxD,label)=>{const to=_tmpV.copy(p).sub(cam.position);const d=to.length();if(d>maxD)return;const along=to.dot(fwd);if(along<0)return;const perp=Math.sqrt(Math.max(0,d*d-along*along));const tol=r+0.12+0.1*d;if(perp<tol){const score=perp/tol+d*0.05;if(!best||score<best.score)best={kind,ref,dist:d,label,score};}};
  for(const o of G.objs){if(o.held!==null&&o.held!==P.id)continue;if(o.carrier)continue;if(o.k!==P.k&&Math.abs(o.p.y-P.pos.y)>2)continue;if(o.id===P.hands)continue;const lbl=o.kind==='prop'?'Grab '+o.prop:(o.value>0?'Pick up '+o.name+' · '+fmt(o.value)+' cr':'Pick up '+(o.name||'item'));consider('obj',o,new THREE.Vector3(o.p.x,o.p.y+o.h/2,o.p.z),o.r+0.15,o.sz>=2?3.2:2.6,lbl);}
  for(const id in G.doors){const d=G.doors[id];if(d.k!==P.k)continue;if(d.broken)continue;const lbl=d.blast?(d.open>0.5?'':(d.locked?'Blast door sealed — restore power':'Open blast door')):(d.locked?(hasKey()?'Unlock red door':'Locked (red)'):(d.open>0.5?'Close door':'Open door'));if(lbl)consider('door',d,new THREE.Vector3(d.x,layerY(d.k)+1.1,d.z),0.7,2.6,lbl);}
  for(const d of G.docs){if(d.k!==P.k||d.read)continue;consider('doc',d,new THREE.Vector3(d.x,layerY(d.k)+0.1,d.z),0.35,2.4,'Read document');}
  const m=G.map;if(m.gen&&m.gen.k===P.k&&!m.gen.on)consider('gen',m.gen,new THREE.Vector3(m.gen.x,layerY(m.gen.k)+0.8,m.gen.z),0.9,3,'Hold E · Restore power');
  {const sg=m.specials&&m.specials.sig;if(sg&&!sg.done){for(const g of sg.gens){if(g.on&&g.k===P.k)consider('siggen',g,new THREE.Vector3(g.x,layerY(g.k)+0.8,g.z),0.9,3,'Hold E · Shut down generator ('+sigFloor(g.k)+')');}if(sg.term&&sg.term.k===P.k)consider('sigterm',sg.term,new THREE.Vector3(sg.term.x,layerY(0)+0.8,sg.term.z),0.8,3,sg.term.read?'Terminal · order noted':'Hold E · Read the terminal');}}
  if(m.specials.terminal&&m.specials.terminal.k===P.k&&!m.specials.terminal.done){const t=m.specials.terminal;consider('term',t,new THREE.Vector3(t.x,layerY(t.k)+1,t.z),0.6,2.6,'Hold E · Download drive');}
  if(m.specials.beacon&&m.specials.beacon.k===P.k&&!m.specials.beacon.done){const t=m.specials.beacon;consider('beac',t,new THREE.Vector3(t.x,layerY(t.k)+1.2,t.z),0.7,2.8,'Hold E · Activate beacon');}
  if(m.hatch&&P.k===0&&!G.mission.hatchUsed)consider('hatch',m.hatch,new THREE.Vector3(m.hatch.x,0.1,m.hatch.z),0.5,2.4,m.hatch.found?'Climb out (emergency hatch)':'Maintenance hatch');
  if(m.elev&&P.k!==undefined){const e=m.elev;const inCab=Math.abs(P.pos.x-e.wx)<1.1&&Math.abs(P.pos.z-e.wz)<1.1;if(inCab)consider('elev',e,new THREE.Vector3(e.wx-0.9,layerY(P.k)+1.3,e.wz+0.9),0.6,2.2,'Elevator · '+(P.k===0?'Descend to bottom':'Up to surface'));}
  if(P.inVan&&G.mission.state==='play'&&!vanLocked())consider('van',null,new THREE.Vector3(m.van.x,1.5,m.van.z+0.3),0.9,2.6,mpHost()||!MP.on?'DEPART ('+readyCount()+' in van)':'Waiting for host to depart ('+readyCount()+' in van)');
  for(const id in G.avatars){const a=G.avatars[id];if(a.k!==P.k)continue;if(a.downed&&!a.dead)consider('revive',a,a.pos.clone().add(new THREE.Vector3(0,0.5,0)),0.8,2.4,'Hold E · Revive '+a.name);else if(P.medkits>0&&a.hp<100&&!a.dead)consider('heal',a,a.pos.clone().add(new THREE.Vector3(0,1,0)),0.6,2.2,'Hold H · Medkit '+a.name);}
  for(const c of G.creatures){if(c.kind==='mimic'&&c.state==='hidden'&&c.k===P.k)consider('mimic',c,c.pos.clone().add(new THREE.Vector3(0,0.35,0)),0.7,3,'Pick up Reinforced Strongbox · 6,500 cr');if(c.kind==='stack'&&c.state==='hidden'&&c.k===P.k)consider('stack',c,c.pos.clone().add(new THREE.Vector3(0,0.4,0)),0.7,3,'Pick up Sealed Container · 3,000 cr');}
  return best;}
function hasKey(){for(const id of P.pockets){const o=G.objById[id];if(o&&o.curse==='redkey')return true;}const h=P.hands&&G.objById[P.hands];return !!(h&&h.curse==='redkey');}
function interact(){if(P.dead)return;const t=lookTarget();if(!t)return;
  if(t.kind==='obj')grabObj(t.ref);
  else if(t.kind==='door')toggleDoor(t.ref);
  else if(t.kind==='doc')readDoc(t.ref);
  else if(t.kind==='hatch'){if(!t.ref.found){t.ref.found=true;toast('🔧 Emergency hatch found — leads to the yard');if(mpHost())bcast({t:'ev',k:'hatch'});else sendAct({k:'hatch'});}else{useHatch();}}
  else if(t.kind==='elev')useElevator();
  else if(t.kind==='van'){if(mpHost()||!MP.on)startDepart();}
  else if(t.kind==='stack'){if(mpHost())stackReveal(t.ref,P.id);else sendAct({k:'stack',id:t.ref.id});}
  else if(t.kind==='mimic'){if(mpHost())mimicTrigger(t.ref,P.id);else sendAct({k:'mimic',id:t.ref.id});}
}
function holdInteract(dt){/* E held: generator/terminal/beacon/revive */const t=lookTarget();if(!t||!(held('interact')||GP.use)){P.useT=0;P.useTarget=null;hidePrompt2();return;}
  if(['gen','term','beac','revive','siggen','sigterm'].indexOf(t.kind)<0){P.useT=0;return;}
  if(P.useTarget!==t.ref){P.useT=0;P.useTarget=t.ref;}
  const need=t.kind==='gen'?6:t.kind==='term'?7:t.kind==='beac'?5:t.kind==='siggen'?6:t.kind==='sigterm'?3:4;P.useT+=dt;if(t.kind==='siggen'){emitNoise(P.pos,P.k,0.9,'machine');if(Math.random()<dt*6)Aud.tone(60+Math.random()*40,0.1,'sawtooth',0.08,null,{lp:300});}
  if(t.kind==='gen'){emitNoise(P.pos,P.k,0.9,'machine');if(Math.random()<dt*6)Aud.tone(80+Math.random()*60,0.1,'sawtooth',0.08,null,{lp:400});}
  if(t.kind==='term'&&Math.random()<dt*4)Aud.tone(1200+Math.random()*800,0.05,'square',0.04);
  $('prompt').textContent=t.label+' '+Math.round(P.useT/need*100)+'%';
  if(P.useT>=need){P.useT=0;if(t.kind==='gen')doPower();else if(t.kind==='term')doTerminal();else if(t.kind==='beac')doBeacon();else if(t.kind==='revive')doRevive(t.ref);else if(t.kind==='siggen')doSigGen(t.ref);else if(t.kind==='sigterm')doSigTerm();}
}
function hidePrompt2(){}
function grabObj(o){if(P.downed&&o.sz>=1)return;
  if(o.sz===0&&canPocket(o)){P.pockets.push(o.id);o.held=P.id;o.lastHolder=P.id;o.mesh.visible=false;Aud.pickup();P.grabAnim=1;updateInv();invPop(P.pockets.length-1);if(mpHost())bcast({t:'ev',k:'held',id:o.id,pid:P.id,pocket:true});else sendAct({k:'grab',id:o.id,pocket:true});onPickup(o);if(o.value>0)floatText('+'+fmt(o.value)+' cr','gold');return;}
  if(o.sz>=3&&MP.on&&Object.keys(MP.players).length>1){/* two-player carry */if(P.hands)dropHands();o.holders.push(P.id);P.hands=o.id;o.lastHolder=P.id;o.sleep=false;if(mpHost())bcast({t:'ev',k:'holders',id:o.id,h:o.holders});else sendAct({k:'grab2',id:o.id});toast(o.holders.length<2?'🫳 Needs two people — call a friend':'🫳 Both carrying — move together');updateInv();onPickup(o);return;}
  if(P.hands){const h=G.objById[P.hands];if(h&&canPocket(h)){P.pockets.push(h.id);h.mesh.visible=false;P.hands=null;netPocket(h);toast('👝 Pocketed '+(h.name||'item'));}else dropHands();}P.hands=o.id;o.held=P.id;o.lastHolder=P.id;o.sleep=false;o.mesh.visible=true;Aud.pickup();P.grabAnim=1;updateInv();if(mpHost())bcast({t:'ev',k:'held',id:o.id,pid:P.id});else sendAct({k:'grab',id:o.id});onPickup(o);if(o.value>0)floatText('+'+fmt(o.value)+' cr'+(o.frag?'  ·  fragile':''),o.frag?'red':'gold');
  if(o.sz>=2)toast('🏋 Heavy. No sprinting, no jumping. Doors are your enemy now.');}
function onPickup(o){G.mission.stats.pickups++;if(o.curse)toast('❓ '+o.name+': '+CURSE_DESC[o.curse]);if(o.curse==='phone'&&!P.curseT.phone)P.curseT.phone=20+Math.random()*40;if(o.curse==='photo'&&!P.curseT.photo)P.curseT.photo=180;if(o.curse==='redkey')G.mission.redkey=true;if(o.special==='tag'){objectiveProgress('researcher');}}
function dropHands(fumble){if(!P.hands)return;const o=G.objById[P.hands];P.hands=null;if(!o)return;o.held=null;o.holders=o.holders.filter(h=>h!==P.id);o.sleep=false;o.v.copy(P.vel);o.harsh=false;o.thrownAt=0;if(fumble){o.v.x+=(Math.random()-0.5)*3;o.v.z+=(Math.random()-0.5)*3;}else if(Math.hypot(P.vel.x,P.vel.z)<4.5){/* set it down gently instead of letting it fall */const gy=groundY(G.map,o.k,o.p.x,o.p.z);o.p.y=Math.max(o.p.y-1.2,gy+o.h*0.5+0.02);o.v.set(P.vel.x*0.4,-0.5,P.vel.z*0.4);if(o.frag)hintOnce('gentle','Dropping sets loot down gently. Hard throws (hold left-click and let fly) are what break fragile things.');}o.mesh.visible=true;Aud.drop(fumble?0.3:0.12,o.p);G.mission.stats.drops++;pstat(P.id,'dropv',o.value);updateInv();if(mpHost())bcast({t:'ev',k:'held',id:o.id,pid:null,p:[o.p.x,o.p.y,o.p.z],v:[o.v.x,o.v.y,o.v.z]});else sendAct({k:'drop',id:o.id,p:[o.p.x,o.p.y,o.p.z],v:[o.v.x,o.v.y,o.v.z]});}
function throwHands(power){if(!P.hands)return;const o=G.objById[P.hands];if(!o)return;if(o.holders.length>=2){dropHands();return;}P.hands=null;o.held=null;o.holders=[];o.sleep=false;const fwd=new THREE.Vector3(0,0,-1).applyQuaternion(G.cam.quaternion);const f=(4+power*10)*clamp(6/o.mass,0.25,1.6);o.harsh=power>=0.45;o.thrownAt=G.t;o.v.copy(fwd).multiplyScalar(f).add(P.vel);o.v.y+=1.5*power;o.spin=(Math.random()-0.5)*8;o.mesh.visible=true;Aud.noise(0.15,0.2,null,{f:1200,type:'highpass'});emitNoise(P.pos,P.k,0.3,'throw');G.mission.stats.thrown++;S.stats.thrown++;pstat(P.id,'thrown',1);if(S.stats.thrown>=50)ach('thrown');updateInv();if(mpHost())bcast({t:'ev',k:'held',id:o.id,pid:null,p:[o.p.x,o.p.y,o.p.z],v:[o.v.x,o.v.y,o.v.z],spin:o.spin});else sendAct({k:'drop',id:o.id,p:[o.p.x,o.p.y,o.p.z],v:[o.v.x,o.v.y,o.v.z],spin:o.spin});}
function takePocket(i){if(P.downed)return;const id=P.pockets[i];if(!id){if(P.hands)pocketHeld();return;}const o=G.objById[id];if(!o)return;P.pockets.splice(i,1);if(P.hands){const h=G.objById[P.hands];if(h&&canPocket(h)){P.pockets.push(h.id);h.mesh.visible=false;netPocket(h);}else dropHands();}P.hands=o.id;o.mesh.visible=true;updateInv();Aud.ui('click');if(mpHost())bcast({t:'ev',k:'held',id:o.id,pid:P.id});else sendAct({k:'grab',id:o.id});}
function stashHands(){pocketHeld();}
function dropAll(){for(const id of P.pockets.slice()){const o=G.objById[id];if(o){o.held=null;o.mesh.visible=true;o.p.copy(P.pos);o.p.y+=0.5;o.v.set((Math.random()-0.5)*2,1,(Math.random()-0.5)*2);o.sleep=false;o.k=P.k;if(mpHost())bcast({t:'ev',k:'held',id:o.id,pid:null,p:[o.p.x,o.p.y,o.p.z],v:[o.v.x,o.v.y,o.v.z]});else sendAct({k:'drop',id:o.id,p:[o.p.x,o.p.y,o.p.z],v:[o.v.x,o.v.y,o.v.z]});}}P.pockets=[];dropHands();updateInv();}
function toggleDoor(d){if(d.blast){if(d.open>0.5)return;if(d.locked){toast('⛔ Sealed. Restore power or find another way.');Aud.ui('bad');return;}setDoor(d,1);return;}
  if(d.jam){toast('🚪 Jammed.');Aud.ui('bad');return;}
  if(d.locked){if(hasKey()){d.locked=false;toast('🗝 The red key turns. Something far away notices.');if(mpHost())G.director.aggro+=0.5;setDoor(d,1);if(mpHost())bcast({t:'ev',k:'unlock',id:d.id});else sendAct({k:'unlock',id:d.id});}else{toast('🔴 Locked. It wants a red key.');Aud.ui('bad');}return;}
  const heavy=P.hands&&G.objById[P.hands]&&G.objById[P.hands].sz>=2;if(heavy&&Math.random()<0.15){toast('🚪 Can\'t get the door with this thing…');Aud.ui('bad');emitNoise(P.pos,P.k,0.4,'door');return;}
  setDoor(d,d.target>0.5?0:1);G.mission.stats.doors++;S.stats.doors++;pstat(P.id,'doors',1);}
function setDoor(d,target,slam){d.target=target;if(target===0&&mpHost())noteDoorClosed(P.id,d);const p=new THREE.Vector3(d.x,layerY(d.k)+1,d.z);Aud.door(p,slam);if(slam)doorSlamFeel(d);emitNoise(p,d.k,slam?0.8:0.2,'door');if(mpHost())bcast({t:'ev',k:'door',id:d.id,o:target,slam:!!slam});else if(MP.on)sendAct({k:'door',id:d.id,o:target});}
function doorSlamFeel(d){if(!d||d.k!==P.k)return;const dd=dist2(P.pos.x,P.pos.z,d.x,d.z);if(dd<8)G.fx.shake+=0.4*(1-dd/8);}
function updateDoors(dt){for(const id in G.doors){const d=G.doors[id];const sp=d.blast?0.6:(d.slamming?9:2.6);d.open=lerp(d.open,d.target,1-Math.exp(-sp*dt));if(Math.abs(d.open-d.target)<0.01)d.open=d.target;
  if(d.blast){if(d.mesh)d.mesh.position.y=d.open*2.55;continue;}
  if(d.mesh)d.mesh.rotation.y=d.baseRot+d.open*Math.PI*0.52*(d.rot===1?-1:1);
  if(d.rattle>0){d.rattle-=dt;if(d.mesh&&d.open<0.2)d.mesh.rotation.y+=Math.sin(G.t*47)*0.022*(d.rot===1?-1:1);if(d.k===P.k&&dist2(P.pos.x,P.pos.z,d.x,d.z)<14&&G.state==='play')hintOnce('doorRattle','Something is working the handle on the other side. Closed doors slow creatures down. They do not stop them.');}
  if(G.mission.weekly==='doors'&&mpHost()&&Math.random()<dt*0.012&&!d.locked){setDoor(d,d.target>0.5?0:1,Math.random()<0.4);}
  /* door hits player */if(!d.blast&&d.target>d.open+0.3&&d.k===P.k){const dd=dist2(P.pos.x,P.pos.z,d.x,d.z);if(dd<0.9&&Math.random()<dt*2){P.vel.x+=(P.pos.x-d.x)*4;P.vel.z+=(P.pos.z-d.z)*4;}}
}}
function readDoc(d){d.read=true;if(d.mesh)d.mesh.visible=false;G.mission.stats.docs++;if(!G.mission.docsRead)G.mission.docsRead=0;G.mission.docsRead++;const L=LORE.find(l=>l.id===d.lore);S.lore[d.lore]=true;S.stats.docs++;if(Object.keys(S.lore).length>=5)ach('lore5');save();showDoc(L);if(mpHost())bcast({t:'ev',k:'doc',id:d.id});else sendAct({k:'doc',id:d.id});}
function showDoc(L){$('docP').innerHTML='<div class="stamp">RECOVERED</div><h4>'+L.t+'</h4>'+L.b.replace(/</g,'&lt;')+'<div style="margin-top:20px;font-size:11px;color:#777">— press any key to close —</div>';$('docScr').classList.add('on');G.paused='doc';document.exitPointerLock();}
function useHatch(){G.mission.hatchUsed=false;fade(1,()=>{P.pos.set(G.map.van.x-6,0,G.map.van.z-1);P.k=0;P.vel.set(0,0,0);fade(0);toast('🌧 You climb out into the rain.');});}
function useElevator(){if(G.elevBusy)return;G.elevBusy=true;const e=G.map.elev;const down=P.k===0;fade(1,()=>{Aud.noise(2.5,0.3,null,{f:200,a:0.5});Aud.tone(50,2.5,'sine',0.2);setTimeout(()=>{let tk=down?G.map.L-1:0;
  const glitch=G.stage>=4&&Math.random()<0.4;if(glitch)tk=ri(Math.random,1,G.map.L-1);P.pos.set(e.wx,layerY(tk),e.wz);P.k=tk;P.vel.set(0,0,0);Aud.tone(880,0.3,'sine',0.1);if(glitch){toast('🛗 That is not the floor you pressed.');if(mpHost())G.director.aggro+=0.3;}fade(0);G.elevBusy=false;emitNoise(P.pos,P.k,0.6,'elevator');onLayerChange();},2600);});}
function doPower(){const g=G.map.gen;g.on=true;Aud.play('generator',new THREE.Vector3(g.x,layerY(g.k)+1,g.z),1);toast('⚡ POWER RESTORED');Aud.ui('ok');Aud.alarm();if(G.map.exit.locked){G.map.exit.locked=false;setDoor(G.map.exit,1);}for(const l of G.lights)if(!l.eaten&&!l.dead){l.on=true;l.emerg=false;}objectiveProgress('power');if(mpHost())bcast({t:'ev',k:'power'});else sendAct({k:'power'});emitNoise(P.pos,P.k,1.0,'machine');if(mpHost())G.director.aggro+=0.6;}
function doTerminal(){const t=G.map.specials.terminal;t.done=true;spawnObj({kind:'item',tpl:17,value:1600,x:t.x,z:t.z-0.8,k:t.k,id:'drive_obj'});toast('💽 Drive ejected — grab it');Aud.ui('ok');if(mpHost())bcast({t:'ev',k:'term'});else sendAct({k:'term'});}
function doBeacon(){const t=G.map.specials.beacon;t.done=true;toast('🚨 BEACON ACTIVE — the site knows you are here');Aud.alarm();objectiveProgress('beacon');emitNoise(P.pos,P.k,1.0,'beacon');if(mpHost()){G.director.aggro+=0.8;bcast({t:'ev',k:'beacon'});}else sendAct({k:'beacon'});}
function doRevive(a){if(mpHost())hostRevive(a.id);else sendAct({k:'revive',id:a.id});S.stats.revives++;ach('revive');}
function useMedkit(){if(P.medkits<=0||P.dead){return;}const t=lookTarget();if(t&&t.kind==='heal'){P.medkits--;if(mpHost())hostHeal(t.ref.id,50);else sendAct({k:'heal',id:t.ref.id});toast('🩹 Patched '+t.ref.name);updateInv();return;}if(P.hp>=100||P.downed)return;P.medkits--;P.hp=Math.min(100,P.hp+50);toast('🩹 Patched up');Aud.sting('revive');updateInv();}
function useFlare(){if(P.flares<=0||P.dead||G.mission.weekly==='noflash'&&false)return;P.flares--;const o=spawnObj({kind:'item',special:'flare',tpl:-1,x:P.pos.x,z:P.pos.z,y:P.pos.y+1.2,k:P.k,id:'fl'+Math.random().toString(36).slice(2,7)});o.name='Flare';o.flare=G.t+45;const fwd=new THREE.Vector3(0,0,-1).applyQuaternion(G.cam.quaternion);o.v.copy(fwd).multiplyScalar(7);o.v.y+=2;G.flareObjs.push(o);if(!Aud.play('flare',null,0.7))Aud.noise(0.4,0.4,null,{f:2500,type:'highpass'});emitNoise(P.pos,P.k,0.6,'flare');updateInv();if(mpHost())bcast({t:'ev',k:'flare',p:[o.p.x,o.p.y,o.p.z],v:[o.v.x,o.v.y,o.v.z],k:P.k,id:o.id});else sendAct({k:'flare',p:[o.p.x,o.p.y,o.p.z],v:[o.v.x,o.v.y,o.v.z],id:o.id});}
function swapBattery(){if(P.spare<=0)return;if(P.batt<0.5||P.radio.batt<0.5){P.spare--;if(P.batt<=P.radio.batt)P.batt=1;else P.radio.batt=1;toast('🔋 Battery swapped');Aud.ui('click');updateInv();}}
function hurt(amt,src){if(P.dead||P.downed&&src!=='bleed')return;const arm=[1,0.85,0.7,0.55][S.up.armor];amt*=arm;P.hp-=amt;P.lastHurtSrc=src;if(P.hp>0&&P.hp<(P.minHp===undefined?101:P.minHp)){P.minHp=P.hp;P.minHpSrc=src;}P.hurtT=1;P.kick=1;G.fx.shake+=Math.min(1.5,amt/30);if(amt>=12&&S.set.hitstop!==false)G.hitStop=Math.min(0.09,0.045+amt/500);Aud.sting('hit');G.mission.stats.damage+=amt;pstat(P.id,'dmg',amt);if(P.hp<=0){P.hp=0;goDown();}updateVitals();if(MP.on&&!mpHost())sendAct({k:'hp',hp:P.hp,dn:P.downed});}
function goDown(){if(P.downed)return;P.downed=true;P.deathSrc=P.lastHurtSrc||'unknown';P.bleed=MP.on&&Object.keys(MP.players).length>1?90:25;$('downed').style.display='block';Aud.sting('down');if(P.hands){const o=G.objById[P.hands];if(o&&o.sz>=1)dropHands(true);}toast('🩸 '+'You are down. Crawl. Yell.');G.mission.stats.downs++;pstat(P.id,'downs',1);if(mpHost())bcast({t:'ev',k:'down',pid:P.id});else sendAct({k:'down'});}
function die(){P.dead=true;P.downed=false;$('downed').style.display='none';dropAll();toast('☠ '+'You died. Spectating.');Aud.sting('scare');G.mission.stats.deaths++;S.deaths++;pstat(P.id,'deaths',1);P.spectate=null;document.body.style.filter='grayscale(0.7)';if(mpHost())bcast({t:'ev',k:'dead',pid:P.id,p:[P.pos.x,P.pos.y,P.pos.z],k2:P.k});else sendAct({k:'dead',p:[P.pos.x,P.pos.y,P.pos.z],k2:P.k});spawnCorpse(P.id,P.pos,P.k);}
function spawnCorpse(pid,pos,k){const r=Assets.rig('player');applyCosmetics(r.root,MP.players[pid]?MP.players[pid].cos:S.cos);r.root.position.copy(pos);r.root.rotation.y=Math.random()*TAU;r.play('dead',0,true);r.mixer.update(1);G.scene.add(r.root);G.corpses=G.corpses||[];G.corpses.push({rig:r,pid});}
function updateSpectate(dt){const ids=Object.keys(G.avatars).filter(id=>!G.avatars[id].dead);if(ids.length){if(!P.spectate||ids.indexOf(P.spectate)<0)P.spectate=ids[0];const a=G.avatars[P.spectate];const bfx=-Math.sin(a.yaw),bfz=-Math.cos(a.yaw);const arm=camArm(a.k,a.pos.x,a.pos.z,bfx,bfz,3.2);const tgt=new THREE.Vector3(a.pos.x-bfx*arm,a.pos.y+1.6+arm*0.25,a.pos.z-bfz*arm);if(P.k!==a.k||!P.specLook){G.cam.position.copy(tgt);P.specLook=new THREE.Vector3(a.pos.x,a.pos.y+1.2,a.pos.z);}else G.cam.position.lerp(tgt,1-Math.exp(-6*dt));P.specLook.lerp(new THREE.Vector3(a.pos.x,a.pos.y+1.2,a.pos.z),1-Math.exp(-10*dt));G.cam.lookAt(P.specLook);P.pos.copy(a.pos);P.k=a.k;}else{/* free fly */const sens=S.set.sens*0.0022;P.yaw-=mouseDX*sens;P.pitch-=mouseDY*sens;mouseDX=mouseDY=0;const fwd=new THREE.Vector3(0,0,-1).applyEuler(new THREE.Euler(P.pitch,P.yaw,0,'YXZ'));let mv=0;if(K.KeyW)mv=1;if(K.KeyS)mv=-1;P.pos.addScaledVector(fwd,mv*8*dt);G.cam.position.copy(P.pos);G.cam.rotation.order='YXZ';G.cam.rotation.set(P.pitch,P.yaw,0);}G.flash.intensity=0;}
/* ---- noise system ---- */
const NOISES=[];
function emitNoise(p,k,loud,kind){if(loud<=0)return;const n={x:p.x,y:p.y!==undefined?p.y:layerY(k),z:p.z,k,loud,kind,t:G.t,pid:P.id};NOISES.push(n);P.lastNoise=Math.max(P.lastNoise*0.5,loud);P.noise=Math.max(P.noise,loud);if(MP.on&&!mpHost()&&loud>=0.25)sendAct({k:'noise',p:[p.x,n.y,p.z],l:k,loud,kind});}
/* ---- curses ---- */
function updateCurses(dt){const held=[...P.pockets,P.hands].map(id=>id&&G.objById[id]).filter(Boolean);
  for(const o of held){if(!o.curse)continue;
    if(o.curse==='tape'&&Math.random()<dt*0.02){toast('📼 The tape clicks on.');echoPlayClip(P.pos.clone(),false,0.5);}
    if(o.curse==='mask'&&Math.random()<dt*0.03){const p=P.pos.clone();p.x+=(Math.random()-0.5)*8;p.z+=(Math.random()-0.5)*8;Aud.creature('laugh',p,0.8);subtitle('[laughter, close]');}
    if(o.curse==='phone'){P.curseT.phone=(P.curseT.phone||30)-dt;if(P.curseT.phone<=0){P.curseT.phone=40+Math.random()*60;P.phoneRinging=G.t+12;Aud.creature('ring',P.pos,1);subtitle('[the black phone is ringing]');toast('☎ It\'s ringing. Press F to answer. Or don\'t.');}}
    if(o.curse==='photo'){P.curseT.photo=(P.curseT.photo||180)-dt;if(P.curseT.photo<=0){P.curseT.photo=9999;toast('🖼 Something has developed in the empty photo. It is a picture of this room.');Aud.creature('window',P.pos,1);}}
    if(o.curse==='watcher'&&Math.random()<dt*0.01){toast('📹 The camera is recording. There is a second figure in the footage.');G.fx.glitch=1;}
  }
  if(P.phoneRinging&&G.t>P.phoneRinging){P.phoneRinging=0;}
}
function answerPhone(){if(!P.phoneRinging)return;P.phoneRinging=0;ach('phone');Aud.radioClick();const r=Math.random();if(r<0.35){subtitle('"…don\'t use the elevator."');toast('☎ A voice. It sounds like you.');echoPlayClip(P.pos.clone(),true,0.9);}else if(r<0.7){subtitle('[breathing]');toast('☎ Breathing. Then a click.');if(mpHost())G.director.aggro+=0.5;else sendAct({k:'aggro',v:0.5});}else{subtitle('"Fourteen thousand. Bring the statue."');toast('☎ A number and an instruction. Your loot value just doubled for 60 seconds.');G.mission.valueBoost=G.t+60;}}

const TOUCH={mx:0,my:0,on:false};
function unstick(){const m=G.map;if(!m||G.state!=='play')return;P.camSnap=true;const k=P.k;const cx0=Math.floor(P.pos.x/CELL),cz0=Math.floor(P.pos.z/CELL);
  for(let r=0;r<=5;r++){for(let dz=-r;dz<=r;dz++)for(let dx=-r;dx<=r;dx++){if(Math.max(Math.abs(dx),Math.abs(dz))!==r)continue;const cx=cx0+dx,cz=cz0+dz;if(cx<0||cz<0||cx>=m.W||cz>=m.H)continue;if(!walkable(m,k,cx,cz))continue;const lay=m.layers[k];if(lay.stairAt&&lay.stairAt[cz*m.W+cx])continue;
    P.pos.x=(cx+0.5)*CELL;P.pos.z=(cz+0.5)*CELL;P.pos.y=layerY(k);P.vel.set(0,0,0);P.stuckT=0;if(P.stuckRef)P.stuckRef.copy(P.pos);toast('🧭 Unstuck.');Aud.ui('click');return;}}
  toast('Could not find open floor nearby.');}

/* your own body, shown in third person (and never counted as another player) */
/* how far back a camera can sit along (-fx,-fz) from (px,pz) on floor k before a wall; 0.1 m march, 0.28 m margin */
function camArm(k,px,pz,fx,fz,maxD){let free=maxD;for(let d=0.15;d<=maxD;d+=0.1){const cx=px-fx*d,cz=pz-fz*d;if(!losClear(G.map,k,px,pz,cx,cz)){free=d-0.1;break;}}return Math.max(0.3,free-0.28);}
function updateSelfAvatar(dt){const want=S.set.tp&&G.state==='play'&&!P.dead&&!P.spectate&&(P.tpDist===undefined||P.tpDist>0.6);if(!G.selfAv){if(!want)return;const r=Assets.rig('player');if(!r)return;applyCosmetics(r.root,sanitizedCos());enhanceRig(r.root,'player');r.root.traverse(o=>{if(o.isMesh||o.isSkinnedMesh){o.castShadow=true;}});G.scene.add(r.root);G.selfAv={rig:r,anim:'idle',cosKey:JSON.stringify(sanitizedCos())};}
  const a=G.selfAv;a.rig.root.visible=want;if(!want)return;{const sc=sanitizedCos();const key=JSON.stringify(sc);if(a.cosKey!==key){applyCosmetics(a.rig.root,sc);a.cosKey=key;}}
  a.rig.root.position.copy(P.pos);a.rig.root.rotation.set(0,P.yaw+Math.PI,0);
  const spd=Math.hypot(P.vel.x,P.vel.z);const held=P.hands&&G.objById[P.hands];let an='idle';if(P.downed)an='crawl';else if(held&&held.sz>=1)an='carry';else if(P.crouch)an='crouch';else if(spd>5)an='run';else if(spd>0.4)an='walk';
  if(an!==a.anim){a.anim=an;a.rig.play(an,0.15,false);}a.rig.mixer.timeScale=(an==='crouch'&&spd<0.3)?0:(an==='walk'||an==='run'?clamp(spd/(an==='run'?6.4:4.1),0.5,1.6):1);a.rig.mixer.update(dt);}
